export type SoundWordPosition = "initial" | "inside";
export type SoundWordLevel = "core" | "extra";
export type SoundRisk = "safe" | "sensitive";

export type SoundWordEntry = {
  word: string;
  position: SoundWordPosition;
  level: SoundWordLevel;
};

export type SoundWordBank = {
  risk: SoundRisk;
  notes?: string;
  words: SoundWordEntry[];
};

function entry(word: string, position: SoundWordPosition, level: SoundWordLevel = "core"): SoundWordEntry {
  return { word, position, level };
}

export const NORWEGIAN_SOUND_WORD_BANKS: Record<string, SoundWordBank> = {
  s: {
    risk: "safe",
    words: [
      entry("sol", "initial"),
      entry("saft", "initial"),
      entry("seng", "initial"),
      entry("sekk", "initial"),
      entry("sko", "initial"),
      entry("suppe", "initial"),
      entry("sitte", "initial"),
      entry("se", "initial"),
      entry("si", "initial"),
      entry("sang", "initial"),
      entry("sommer", "initial"),
      entry("skole", "initial"),
      entry("stol", "initial"),
      entry("sulten", "initial"),
      entry("søt", "initial"),
      entry("buss", "inside"),
      entry("hus", "inside"),
      entry("lese", "inside"),
      entry("pose", "inside"),
      entry("danse", "inside"),
      entry("fisk", "inside"),
      entry("ost", "inside"),
      entry("klasse", "inside"),
      entry("bestemor", "inside"),
      entry("hest", "inside"),
      entry("is", "inside"),
    ],
  },
  m: {
    risk: "safe",
    words: [
      entry("mat", "initial"),
      entry("mor", "initial"),
      entry("mus", "initial"),
      entry("melk", "initial"),
      entry("mål", "initial"),
      entry("mye", "initial"),
      entry("min", "initial"),
      entry("mitt", "initial"),
      entry("måne", "initial"),
      entry("mann", "initial"),
      entry("mamma", "initial"),
      entry("morgen", "initial"),
      entry("munn", "initial"),
      entry("med", "initial"),
      entry("møter", "initial"),
      entry("rom", "inside"),
      entry("hjem", "inside"),
      entry("sommer", "inside"),
      entry("familie", "inside"),
      entry("komme", "inside"),
      entry("lampe", "inside"),
      entry("nummer", "inside"),
      entry("gammel", "inside"),
      entry("klemme", "inside"),
      entry("lomme", "inside"),
      entry("tomat", "inside"),
    ],
  },
  a: {
    risk: "safe",
    words: [
      entry("and", "initial"),
      entry("ape", "initial"),
      entry("arm", "initial"),
      entry("ark", "initial"),
      entry("alle", "initial"),
      entry("Anna", "initial"),
      entry("Ali", "initial"),
      entry("av", "initial"),
      entry("at", "initial"),
      entry("appelsin", "initial"),
      entry("arbeid", "initial"),
      entry("ansikt", "initial"),
      entry("aldri", "initial"),
      entry("alltid", "initial"),
      entry("mat", "inside"),
      entry("Sara", "inside"),
      entry("banan", "inside"),
      entry("kake", "inside"),
      entry("glad", "inside"),
      entry("dag", "inside"),
      entry("pappa", "inside"),
      entry("mamma", "inside"),
      entry("familie", "inside"),
      entry("salat", "inside"),
      entry("hatt", "inside"),
      entry("jakke", "inside"),
    ],
  },
  b: {
    risk: "safe",
    words: [
      entry("bil", "initial"),
      entry("bok", "initial"),
      entry("ball", "initial"),
      entry("bord", "initial"),
      entry("buss", "initial"),
      entry("barn", "initial"),
      entry("brød", "initial"),
      entry("båt", "initial"),
      entry("ben", "initial"),
      entry("blå", "initial"),
      entry("butikk", "initial"),
      entry("bamse", "initial"),
      entry("bade", "initial"),
      entry("bilde", "initial"),
      entry("bak", "initial"),
      entry("jobb", "inside"),
      entry("kube", "inside"),
      entry("robot", "inside"),
      entry("tabell", "inside"),
      entry("nabo", "inside"),
      entry("skrubbe", "inside", "extra"),
      entry("krabbe", "inside"),
      entry("lommebok", "inside"),
    ],
  },
  d: {
    risk: "safe",
    words: [
      entry("dag", "initial"),
      entry("du", "initial"),
      entry("din", "initial"),
      entry("dyr", "initial"),
      entry("dør", "initial"),
      entry("dans", "initial"),
      entry("dukke", "initial"),
      entry("drue", "initial"),
      entry("drikke", "initial"),
      entry("dele", "initial"),
      entry("der", "initial"),
      entry("dame", "initial"),
      entry("datter", "initial"),
      entry("data", "initial"),
      entry("dusj", "initial"),
      entry("skade", "inside"),
      entry("bilde", "inside"),
      entry("side", "inside"),
      entry("hode", "inside"),
      entry("middag", "inside"),
      entry("bade", "inside"),
      entry("nede", "inside"),
      entry("redde", "inside"),
      entry("rydde", "inside"),
      entry("lyd", "inside"),
    ],
  },
  f: {
    risk: "safe",
    words: [
      entry("far", "initial"),
      entry("fisk", "initial"),
      entry("fot", "initial"),
      entry("fin", "initial"),
      entry("fugl", "initial"),
      entry("fem", "initial"),
      entry("frokost", "initial"),
      entry("frukt", "initial"),
      entry("farge", "initial"),
      entry("får", "initial"),
      entry("familie", "initial"),
      entry("finner", "initial"),
      entry("fart", "initial"),
      entry("fryser", "initial"),
      entry("følge", "initial"),
      entry("kaffe", "inside"),
      entry("sofa", "inside"),
      entry("telefon", "inside"),
      entry("vaffel", "inside"),
      entry("skuff", "inside"),
      entry("tøff", "inside"),
      entry("loft", "inside"),
      entry("saft", "inside"),
      entry("ofte", "inside"),
      entry("lufte", "inside"),
    ],
  },
  g: {
    risk: "safe",
    words: [
      entry("gå", "initial"),
      entry("god", "initial"),
      entry("gul", "initial"),
      entry("gris", "initial"),
      entry("gutt", "initial"),
      entry("gate", "initial"),
      entry("gave", "initial"),
      entry("genser", "initial"),
      entry("glass", "initial"),
      entry("glede", "initial"),
      entry("grøt", "initial"),
      entry("grønn", "initial"),
      entry("gammel", "initial"),
      entry("gitar", "initial"),
      entry("gulrot", "initial"),
      entry("dag", "inside"),
      entry("tog", "inside"),
      entry("hage", "inside"),
      entry("mage", "inside"),
      entry("farge", "inside"),
      entry("morgen", "inside"),
      entry("legge", "inside"),
      entry("ligge", "inside"),
      entry("fugl", "inside"),
      entry("rolig", "inside"),
      entry("sag", "inside"),
    ],
  },
  k: {
    risk: "sensitive",
    notes: "Plain k should not mix with kj/skj words.",
    words: [
      entry("katt", "initial"),
      entry("kake", "initial"),
      entry("kopp", "initial"),
      entry("kul", "initial"),
      entry("kan", "initial"),
      entry("kommer", "initial"),
      entry("kald", "initial"),
      entry("kort", "initial"),
      entry("klasse", "initial"),
      entry("klokke", "initial"),
      entry("kropp", "initial"),
      entry("klem", "initial"),
      entry("kveld", "initial"),
      entry("ku", "initial"),
      entry("bok", "inside"),
      entry("tak", "inside"),
      entry("pakke", "inside"),
      entry("sokker", "inside"),
      entry("drikke", "inside"),
      entry("skole", "inside"),
      entry("voksen", "inside"),
      entry("lek", "inside"),
      entry("frokost", "inside"),
      entry("matpakke", "inside"),
      entry("jakke", "inside"),
    ],
  },
  n: {
    risk: "safe",
    words: [
      entry("natt", "initial"),
      entry("nese", "initial"),
      entry("navn", "initial"),
      entry("ni", "initial"),
      entry("ny", "initial"),
      entry("norsk", "initial"),
      entry("nøkkel", "initial"),
      entry("nabo", "initial"),
      entry("natur", "initial"),
      entry("nå", "initial"),
      entry("nær", "initial"),
      entry("ned", "initial"),
      entry("noen", "initial"),
      entry("Nina", "initial"),
      entry("notat", "initial"),
      entry("banan", "inside"),
      entry("vann", "inside"),
      entry("venn", "inside"),
      entry("mann", "inside"),
      entry("hund", "inside"),
      entry("kanin", "inside"),
      entry("måne", "inside"),
      entry("panne", "inside"),
      entry("fin", "inside"),
      entry("grønn", "inside"),
      entry("barn", "inside"),
    ],
  },
  e: {
    risk: "safe",
    words: [
      entry("egg", "initial"),
      entry("en", "initial"),
      entry("et", "initial"),
      entry("eple", "initial"),
      entry("elefant", "initial"),
      entry("elleve", "initial"),
      entry("etter", "initial"),
      entry("elev", "initial"),
      entry("egen", "initial"),
      entry("enkel", "initial"),
      entry("elsker", "initial"),
      entry("eske", "initial"),
      entry("elv", "initial"),
      entry("ende", "initial"),
      entry("er", "initial"),
      entry("se", "inside"),
      entry("leke", "inside"),
      entry("lese", "inside"),
      entry("seng", "inside"),
      entry("bestemor", "inside"),
      entry("venn", "inside"),
      entry("melk", "inside"),
      entry("hest", "inside"),
      entry("lek", "inside"),
      entry("pen", "inside"),
      entry("del", "inside"),
    ],
  },
  o: {
    risk: "safe",
    words: [
      entry("ost", "initial"),
      entry("ord", "initial"),
      entry("Ole", "initial"),
      entry("Oda", "initial"),
      entry("opp", "initial"),
      entry("onkel", "initial"),
      entry("onsdag", "initial"),
      entry("område", "initial"),
      entry("okse", "initial"),
      entry("om", "initial"),
      entry("sol", "inside"),
      entry("sko", "inside"),
      entry("bok", "inside"),
      entry("bord", "inside"),
      entry("mor", "inside"),
      entry("bror", "inside"),
      entry("pose", "inside"),
      entry("jobb", "inside"),
      entry("robot", "inside"),
      entry("foto", "inside"),
      entry("to", "inside"),
      entry("ro", "inside"),
      entry("bo", "inside"),
      entry("bor", "inside"),
      entry("stor", "inside"),
      entry("god", "inside"),
    ],
  },
  u: {
    risk: "safe",
    words: [
      entry("ut", "initial"),
      entry("ull", "initial"),
      entry("uke", "initial"),
      entry("under", "initial"),
      entry("ute", "initial"),
      entry("uten", "initial"),
      entry("ulv", "initial"),
      entry("Ulla", "initial"),
      entry("ugle", "initial"),
      entry("usikker", "initial"),
      entry("univers", "initial", "extra"),
      entry("unik", "initial", "extra"),
      entry("utstyr", "initial"),
      entry("hus", "inside"),
      entry("buss", "inside"),
      entry("suppe", "inside"),
      entry("gul", "inside"),
      entry("tur", "inside"),
      entry("hund", "inside"),
      entry("lunsj", "inside"),
      entry("frukt", "inside"),
      entry("brun", "inside"),
      entry("mus", "inside"),
      entry("du", "inside"),
    ],
  },
  æ: {
    risk: "safe",
    words: [
      entry("ærlig", "initial"),
      entry("ærend", "initial"),
      entry("her", "initial"),
      entry("der", "initial"),
      entry("er", "initial"),
      entry("bær", "inside"),
      entry("vær", "inside"),
      entry("nær", "inside"),
      entry("lærer", "inside"),
      entry("klær", "inside"),
      entry("tær", "inside"),
      entry("kjær", "inside"),
      entry("været", "inside"),
      entry("stjerne", "inside"),
      entry("sær", "inside", "extra"),
      entry("ære", "inside", "extra"),
    ],
  },
  ø: {
    risk: "safe",
    words: [
      entry("øye", "initial"),
      entry("øre", "initial"),
      entry("øy", "initial"),
      entry("øve", "initial"),
      entry("ønske", "initial"),
      entry("øse", "initial"),
      entry("søt", "inside"),
      entry("brød", "inside"),
      entry("grøt", "inside"),
      entry("følge", "inside"),
      entry("møte", "inside"),
      entry("rød", "inside"),
      entry("grønn", "inside"),
      entry("løpe", "inside"),
      entry("høre", "inside"),
      entry("bøker", "inside"),
      entry("dør", "inside"),
      entry("søster", "inside"),
      entry("høne", "inside"),
      entry("skjørt", "inside"),
      entry("kjøkken", "inside"),
      entry("kjøpe", "inside"),
    ],
  },
  å: {
    risk: "safe",
    words: [
      entry("å", "initial"),
      entry("år", "initial"),
      entry("åtte", "initial"),
      entry("ål", "initial", "extra"),
      entry("båt", "inside"),
      entry("blå", "inside"),
      entry("får", "inside"),
      entry("går", "inside"),
      entry("står", "inside"),
      entry("må", "inside"),
      entry("nå", "inside"),
      entry("så", "inside"),
      entry("på", "inside"),
      entry("låne", "inside"),
      entry("måne", "inside"),
      entry("hår", "inside"),
      entry("tå", "inside"),
      entry("våt", "inside"),
      entry("grå", "inside"),
      entry("små", "inside"),
    ],
  },
  sj: {
    risk: "sensitive",
    notes: "The Norwegian sj sound can be written sj, skj and some sk before front vowels.",
    words: [
      entry("sjakk", "initial"),
      entry("sjal", "initial"),
      entry("sjef", "initial"),
      entry("sjekk", "initial"),
      entry("sjekke", "initial"),
      entry("sjekkliste", "initial", "extra"),
      entry("sjokolade", "initial"),
      entry("sjokoladepudding", "initial", "extra"),
      entry("sjø", "initial"),
      entry("sjømann", "initial", "extra"),
      entry("sjåfør", "initial"),
      entry("sjampo", "initial"),
      entry("sjarm", "initial", "extra"),
      entry("skjegg", "initial"),
      entry("skje", "initial"),
      entry("skjell", "initial"),
      entry("skjerm", "initial"),
      entry("skjorte", "initial"),
      entry("skjørt", "initial"),
      entry("skjære", "initial"),
      entry("ski", "initial"),
      entry("skilt", "initial"),
      entry("skinke", "initial"),
      entry("skinn", "initial", "extra"),
      entry("sky", "initial"),
      entry("skygge", "initial"),
      entry("kanskje", "inside"),
      entry("maskin", "inside"),
      entry("dusje", "inside"),
      entry("garasje", "inside"),
      entry("brosjyre", "inside", "extra"),
    ],
  },
  kj: {
    risk: "sensitive",
    notes: "Keep kj separate from k and sj/skj words.",
    words: [
      entry("kjole", "initial"),
      entry("kjøkken", "initial"),
      entry("kjøtt", "initial"),
      entry("kjeks", "initial"),
      entry("kjekk", "initial"),
      entry("kjenne", "initial"),
      entry("kjøpe", "initial"),
      entry("kjøre", "initial"),
      entry("kjede", "initial"),
      entry("kjeller", "initial"),
      entry("kjølig", "initial", "extra"),
      entry("kjapp", "initial"),
      entry("Kjell", "initial"),
      entry("kjele", "initial"),
      entry("kjæledyr", "initial"),
      entry("kjøleskap", "initial"),
      entry("kjempe", "initial"),
      entry("kjempefin", "initial"),
      entry("kjent", "initial"),
      entry("kjenner", "initial"),
      entry("kjempestor", "initial", "extra"),
      entry("bikkje", "inside"),
    ],
  },
};

export const ENGLISH_SOUND_WORD_BANKS: Record<string, SoundWordBank> = {
  "short a / cat": {
    risk: "sensitive",
    notes: "Use short a as in cat. Avoid long-a spellings such as cake/name and broad-a words such as father.",
    words: [
      entry("apple", "initial"),
      entry("ant", "initial"),
      entry("at", "initial"),
      entry("am", "initial"),
      entry("ask", "initial"),
      entry("Anna", "initial"),
      entry("animal", "initial"),
      entry("cat", "inside"),
      entry("hat", "inside"),
      entry("bag", "inside"),
      entry("map", "inside"),
      entry("sad", "inside"),
      entry("jam", "inside"),
      entry("mat", "inside"),
      entry("dad", "inside"),
      entry("hand", "inside"),
      entry("sand", "inside"),
      entry("fan", "inside"),
      entry("pan", "inside"),
      entry("can", "inside"),
    ],
  },
  "short e / bed": {
    risk: "sensitive",
    notes: "Use short e as in bed. Avoid long-e spellings such as me/see and silent-e words.",
    words: [
      entry("egg", "initial"),
      entry("end", "initial"),
      entry("Emma", "initial"),
      entry("every", "initial"),
      entry("bed", "inside"),
      entry("red", "inside"),
      entry("pen", "inside"),
      entry("ten", "inside"),
      entry("pet", "inside"),
      entry("wet", "inside"),
      entry("leg", "inside"),
      entry("yes", "inside"),
      entry("get", "inside"),
      entry("net", "inside"),
      entry("desk", "inside"),
      entry("help", "inside"),
      entry("friend", "inside"),
      entry("best", "inside"),
      entry("head", "inside"),
      entry("bread", "inside"),
    ],
  },
  "short i / sit": {
    risk: "sensitive",
    notes: "Use short i as in sit. Avoid long-i spellings such as bike/time.",
    words: [
      entry("in", "initial"),
      entry("is", "initial"),
      entry("it", "initial"),
      entry("if", "initial"),
      entry("ill", "initial"),
      entry("inside", "initial"),
      entry("sit", "inside"),
      entry("six", "inside"),
      entry("fish", "inside"),
      entry("pig", "inside"),
      entry("big", "inside"),
      entry("ship", "inside"),
      entry("chip", "inside"),
      entry("kid", "inside"),
      entry("miss", "inside"),
      entry("swim", "inside"),
      entry("with", "inside"),
      entry("little", "inside"),
      entry("window", "inside"),
      entry("dinner", "inside"),
    ],
  },
  "short o / dog": {
    risk: "sensitive",
    notes: "Use short o as in dog/hot. Avoid long-o words such as home/go and r-controlled o words.",
    words: [
      entry("dog", "initial"),
      entry("on", "initial"),
      entry("off", "initial"),
      entry("hot", "initial"),
      entry("box", "initial"),
      entry("pot", "initial"),
      entry("sock", "initial"),
      entry("shop", "initial"),
      entry("not", "initial"),
      entry("frog", "inside"),
      entry("clock", "inside"),
      entry("rock", "inside"),
      entry("pond", "inside"),
      entry("top", "inside"),
      entry("Tom", "inside"),
      entry("mom", "inside"),
    ],
  },
  "short u / sun": {
    risk: "sensitive",
    notes: "Use short u as in sun/cup. Avoid long-u words such as cute/use.",
    words: [
      entry("up", "initial"),
      entry("us", "initial"),
      entry("under", "initial"),
      entry("uncle", "initial"),
      entry("sun", "inside"),
      entry("cup", "inside"),
      entry("run", "inside"),
      entry("fun", "inside"),
      entry("cut", "inside"),
      entry("mud", "inside"),
      entry("nut", "inside"),
      entry("duck", "inside"),
      entry("jump", "inside"),
      entry("bus", "inside"),
      entry("lunch", "inside"),
      entry("much", "inside"),
      entry("brush", "inside"),
      entry("drum", "inside"),
    ],
  },
  "long a / cake": {
    risk: "sensitive",
    notes: "Use long a as in cake/name/day. Avoid short-a words such as cat/apple.",
    words: [
      entry("age", "initial"),
      entry("April", "initial"),
      entry("Amy", "initial"),
      entry("ate", "initial"),
      entry("cake", "inside"),
      entry("name", "inside"),
      entry("day", "inside"),
      entry("play", "inside"),
      entry("game", "inside"),
      entry("rain", "inside"),
      entry("train", "inside"),
      entry("table", "inside"),
      entry("baby", "inside"),
      entry("paper", "inside"),
      entry("make", "inside"),
      entry("take", "inside"),
      entry("same", "inside"),
      entry("late", "inside"),
    ],
  },
  "long e / see": {
    risk: "sensitive",
    notes: "Use long e as in see/tree/eat. Avoid short-e words such as bed/pen.",
    words: [
      entry("eat", "initial"),
      entry("each", "initial"),
      entry("easy", "initial"),
      entry("evening", "initial"),
      entry("see", "inside"),
      entry("tree", "inside"),
      entry("green", "inside"),
      entry("three", "inside"),
      entry("sleep", "inside"),
      entry("read", "inside"),
      entry("teacher", "inside"),
      entry("beach", "inside"),
      entry("team", "inside"),
      entry("feet", "inside"),
      entry("cheese", "inside"),
      entry("please", "inside"),
      entry("me", "inside"),
      entry("we", "inside"),
      entry("she", "inside"),
      entry("he", "inside"),
    ],
  },
  "long i / bike": {
    risk: "sensitive",
    notes: "Use long i as in bike/time/my. Avoid short-i words such as sit/fish.",
    words: [
      entry("I", "initial"),
      entry("ice", "initial"),
      entry("idea", "initial"),
      entry("island", "initial"),
      entry("bike", "inside"),
      entry("time", "inside"),
      entry("five", "inside"),
      entry("nine", "inside"),
      entry("kite", "inside"),
      entry("like", "inside"),
      entry("line", "inside"),
      entry("white", "inside"),
      entry("night", "inside"),
      entry("ride", "inside"),
      entry("smile", "inside"),
      entry("nice", "inside"),
      entry("rice", "inside"),
      entry("child", "inside"),
      entry("find", "inside"),
      entry("my", "inside"),
    ],
  },
  "long o / home": {
    risk: "sensitive",
    notes: "Use long o as in home/go/nose. Avoid short-o words such as dog/hot.",
    words: [
      entry("old", "initial"),
      entry("open", "initial"),
      entry("over", "initial"),
      entry("only", "initial"),
      entry("go", "inside"),
      entry("no", "inside"),
      entry("home", "inside"),
      entry("nose", "inside"),
      entry("phone", "inside"),
      entry("stone", "inside"),
      entry("boat", "inside"),
      entry("coat", "inside"),
      entry("road", "inside"),
      entry("snow", "inside"),
      entry("window", "inside"),
      entry("yellow", "inside"),
      entry("slow", "inside"),
      entry("show", "inside"),
    ],
  },
  "long u / cute": {
    risk: "sensitive",
    notes: "Use long u as in cute/use/music. Avoid short-u words such as sun/cup.",
    words: [
      entry("use", "initial"),
      entry("unit", "initial"),
      entry("uniform", "initial"),
      entry("usually", "initial"),
      entry("cute", "inside"),
      entry("music", "inside"),
      entry("student", "inside"),
      entry("June", "inside"),
      entry("cube", "inside"),
      entry("huge", "inside"),
      entry("tube", "inside"),
      entry("computer", "inside"),
      entry("menu", "inside"),
      entry("pupil", "inside"),
    ],
  },
  "oo / moon": {
    risk: "sensitive",
    notes: "Use long oo as in moon/food. Avoid short oo words such as book/look/good.",
    words: [
      entry("moon", "initial"),
      entry("noon", "initial"),
      entry("soon", "initial"),
      entry("room", "inside"),
      entry("food", "inside"),
      entry("school", "inside"),
      entry("cool", "inside"),
      entry("pool", "inside"),
      entry("spoon", "inside"),
      entry("zoo", "inside"),
      entry("too", "inside"),
      entry("boot", "inside"),
    ],
  },
  "oo / book": {
    risk: "sensitive",
    notes: "Use short oo as in book/look/good. Avoid long oo words such as moon/food/school.",
    words: [
      entry("book", "initial"),
      entry("look", "initial"),
      entry("good", "initial"),
      entry("cook", "initial"),
      entry("foot", "inside"),
      entry("wood", "inside"),
      entry("hood", "inside"),
      entry("hook", "inside"),
      entry("took", "inside"),
      entry("stood", "inside"),
    ],
  },
  "ea / bread": {
    risk: "sensitive",
    notes: "Use ea with short e as in bread/head. Avoid long e words such as eat/read/teacher.",
    words: [
      entry("head", "initial"),
      entry("heavy", "initial"),
      entry("healthy", "initial"),
      entry("bread", "inside"),
      entry("ready", "inside"),
      entry("breakfast", "inside"),
      entry("weather", "inside"),
      entry("sweater", "inside"),
      entry("feather", "inside"),
      entry("treasure", "inside"),
    ],
  },
  "er / bird": {
    risk: "sensitive",
    notes: "Use r-controlled vowel as in bird/her/first. Avoid simple short-e words such as bed/pen.",
    words: [
      entry("her", "initial"),
      entry("bird", "inside"),
      entry("girl", "inside"),
      entry("first", "inside"),
      entry("shirt", "inside"),
      entry("skirt", "inside"),
      entry("turn", "inside"),
      entry("nurse", "inside"),
      entry("purple", "inside"),
      entry("circle", "inside"),
      entry("word", "inside"),
      entry("work", "inside"),
    ],
  },
  "or / fork": {
    risk: "sensitive",
    notes: "Use or as in fork/short/morning. Avoid unstressed or words where the vowel is weak.",
    words: [
      entry("or", "initial"),
      entry("fork", "inside"),
      entry("short", "inside"),
      entry("corn", "inside"),
      entry("horse", "inside"),
      entry("morning", "inside"),
      entry("story", "inside"),
      entry("door", "inside"),
      entry("floor", "inside"),
      entry("more", "inside"),
      entry("north", "inside"),
      entry("sport", "inside"),
    ],
  },
  "ar / car": {
    risk: "sensitive",
    notes: "Use ar as in car/farm/park. Avoid short-a words such as cat/bag.",
    words: [
      entry("are", "initial"),
      entry("arm", "initial"),
      entry("art", "initial"),
      entry("car", "inside"),
      entry("park", "inside"),
      entry("farm", "inside"),
      entry("star", "inside"),
      entry("card", "inside"),
      entry("garden", "inside"),
      entry("party", "inside"),
      entry("dark", "inside"),
      entry("smart", "inside"),
    ],
  },
  "ai / rain": {
    risk: "sensitive",
    notes: "Use ai with long a as in rain/train. Avoid short-a words such as cat and non-ai long-a words if possible.",
    words: [
      entry("aim", "initial"),
      entry("aid", "initial"),
      entry("rain", "inside"),
      entry("train", "inside"),
      entry("wait", "inside"),
      entry("paint", "inside"),
      entry("mail", "inside"),
      entry("tail", "inside"),
      entry("sail", "inside"),
      entry("nail", "inside"),
      entry("pain", "inside"),
      entry("snail", "inside"),
    ],
  },
  "ay / day": {
    risk: "sensitive",
    notes: "Use ay with long a as in day/play. Avoid short-a words such as cat and non-ay long-a words if possible.",
    words: [
      entry("day", "inside"),
      entry("play", "inside"),
      entry("say", "inside"),
      entry("way", "inside"),
      entry("May", "inside"),
      entry("stay", "inside"),
      entry("today", "inside"),
      entry("away", "inside"),
      entry("gray", "inside"),
      entry("tray", "inside"),
      entry("pay", "inside"),
      entry("clay", "inside"),
    ],
  },
  "ee / tree": {
    risk: "sensitive",
    notes: "Use ee with long e as in tree/see. Avoid short-e words such as bed and other long-e spellings if possible.",
    words: [
      entry("eel", "initial"),
      entry("see", "inside"),
      entry("tree", "inside"),
      entry("green", "inside"),
      entry("three", "inside"),
      entry("sleep", "inside"),
      entry("feet", "inside"),
      entry("meet", "inside"),
      entry("seed", "inside"),
      entry("bee", "inside"),
      entry("free", "inside"),
      entry("week", "inside"),
    ],
  },
  "oa / boat": {
    risk: "sensitive",
    notes: "Use oa with long o as in boat/coat. Avoid short-o words such as dog and other long-o spellings if possible.",
    words: [
      entry("oak", "initial"),
      entry("oat", "initial"),
      entry("boat", "inside"),
      entry("coat", "inside"),
      entry("road", "inside"),
      entry("goat", "inside"),
      entry("soap", "inside"),
      entry("toast", "inside"),
      entry("goal", "inside"),
      entry("float", "inside"),
      entry("coach", "inside"),
      entry("loaf", "inside"),
    ],
  },
  "ow / snow": {
    risk: "sensitive",
    notes: "Use ow with long o as in snow/window/yellow. Avoid ow with /ou/ as in cow/how/now.",
    words: [
      entry("own", "initial"),
      entry("snow", "inside"),
      entry("window", "inside"),
      entry("yellow", "inside"),
      entry("slow", "inside"),
      entry("show", "inside"),
      entry("grow", "inside"),
      entry("bowl", "inside"),
      entry("pillow", "inside"),
      entry("shadow", "inside"),
      entry("throw", "inside"),
      entry("low", "inside"),
    ],
  },
  "igh / night": {
    risk: "sensitive",
    notes: "Use igh with long i as in night/light. Avoid short-i words such as sit/fish and other long-i spellings if possible.",
    words: [
      entry("night", "inside"),
      entry("light", "inside"),
      entry("right", "inside"),
      entry("bright", "inside"),
      entry("high", "inside"),
      entry("sigh", "inside"),
      entry("fight", "inside"),
      entry("sight", "inside"),
      entry("tight", "inside"),
      entry("might", "inside"),
    ],
  },
  "oi / coin": {
    risk: "sensitive",
    notes: "Use oi as in coin/voice. Avoid oy words if possible so the spelling pattern stays visible.",
    words: [
      entry("oil", "initial"),
      entry("coin", "inside"),
      entry("voice", "inside"),
      entry("point", "inside"),
      entry("join", "inside"),
      entry("boil", "inside"),
      entry("soil", "inside"),
      entry("choice", "inside"),
      entry("noise", "inside"),
      entry("toilet", "inside"),
    ],
  },
  "oy / boy": {
    risk: "sensitive",
    notes: "Use oy as in boy/toy. Avoid oi words if possible so the spelling pattern stays visible.",
    words: [
      entry("boy", "inside"),
      entry("toy", "inside"),
      entry("joy", "inside"),
      entry("enjoy", "inside"),
      entry("royal", "inside"),
      entry("loyal", "inside"),
      entry("Roy", "inside"),
    ],
  },
  "ou / house": {
    risk: "sensitive",
    notes: "Use ou as in house/mouse. Avoid long-oo ou words such as soup/group and long-o words such as soul.",
    words: [
      entry("out", "initial"),
      entry("our", "initial"),
      entry("ouch", "initial"),
      entry("house", "inside"),
      entry("mouse", "inside"),
      entry("mouth", "inside"),
      entry("cloud", "inside"),
      entry("loud", "inside"),
      entry("sound", "inside"),
      entry("round", "inside"),
      entry("ground", "inside"),
      entry("count", "inside"),
    ],
  },
  "ow / cow": {
    risk: "sensitive",
    notes: "Use ow with /ou/ as in cow/how/now. Avoid long-o ow words such as snow/window/yellow.",
    words: [
      entry("owl", "initial"),
      entry("cow", "inside"),
      entry("how", "inside"),
      entry("now", "inside"),
      entry("down", "inside"),
      entry("town", "inside"),
      entry("brown", "inside"),
      entry("flower", "inside"),
      entry("towel", "inside"),
      entry("power", "inside"),
      entry("crowd", "inside"),
      entry("clown", "inside"),
    ],
  },
  "air / chair": {
    risk: "sensitive",
    notes: "Use air/ear/are words with the air sound as in chair/hair/bear/care. Keep this separate from ear as in hear.",
    words: [
      entry("air", "initial"),
      entry("chair", "inside"),
      entry("hair", "inside"),
      entry("pair", "inside"),
      entry("stairs", "inside"),
      entry("fair", "inside"),
      entry("bear", "inside"),
      entry("pear", "inside"),
      entry("wear", "inside"),
      entry("care", "inside"),
      entry("share", "inside"),
      entry("square", "inside"),
    ],
  },
  "ear / hear": {
    risk: "sensitive",
    notes: "Use ear/eer words with the hear sound. Avoid air-sound words such as bear/pear/wear.",
    words: [
      entry("ear", "initial"),
      entry("hear", "inside"),
      entry("near", "inside"),
      entry("dear", "inside"),
      entry("year", "inside"),
      entry("clear", "inside"),
      entry("fear", "inside"),
      entry("tear", "inside"),
      entry("cheer", "inside"),
      entry("deer", "inside"),
      entry("peer", "inside"),
    ],
  },
  "are / care": {
    risk: "sensitive",
    notes: "Use are with the air sound as in care/share/square. Avoid are pronounced /ar/ as in are.",
    words: [
      entry("care", "inside"),
      entry("share", "inside"),
      entry("square", "inside"),
      entry("scare", "inside"),
      entry("bare", "inside"),
      entry("rare", "inside"),
      entry("dare", "inside"),
      entry("prepare", "inside"),
    ],
  },
  m: {
    risk: "safe",
    words: [
      entry("mom", "initial"),
      entry("man", "initial"),
      entry("milk", "initial"),
      entry("map", "initial"),
      entry("moon", "initial"),
      entry("me", "initial"),
      entry("my", "initial"),
      entry("make", "initial"),
      entry("more", "initial"),
      entry("morning", "initial"),
      entry("mouse", "initial"),
      entry("music", "initial"),
      entry("meal", "initial"),
      entry("home", "inside"),
      entry("family", "inside"),
      entry("summer", "inside"),
      entry("swim", "inside"),
      entry("room", "inside"),
      entry("game", "inside"),
      entry("name", "inside"),
      entry("come", "inside"),
      entry("lemon", "inside"),
    ],
  },
  s: {
    risk: "safe",
    words: [
      entry("sun", "initial"),
      entry("sit", "initial"),
      entry("see", "initial"),
      entry("sand", "initial"),
      entry("sock", "initial"),
      entry("soup", "initial"),
      entry("sad", "initial"),
      entry("sing", "initial"),
      entry("school", "initial"),
      entry("small", "initial"),
      entry("sister", "initial"),
      entry("six", "initial"),
      entry("soon", "initial"),
      entry("story", "initial"),
      entry("sleep", "initial"),
      entry("bus", "inside"),
      entry("house", "inside"),
      entry("pencil", "inside"),
      entry("dress", "inside"),
      entry("yes", "inside"),
      entry("horse", "inside"),
    ],
  },
  b: {
    risk: "safe",
    words: [
      entry("big", "initial"),
      entry("bag", "initial"),
      entry("ball", "initial"),
      entry("bed", "initial"),
      entry("bus", "initial"),
      entry("book", "initial"),
      entry("boy", "initial"),
      entry("baby", "initial"),
      entry("blue", "initial"),
      entry("bird", "initial"),
      entry("box", "initial"),
      entry("bread", "initial"),
      entry("bike", "initial"),
      entry("bath", "initial"),
      entry("Ben", "initial"),
      entry("table", "inside"),
      entry("rabbit", "inside"),
      entry("cabin", "inside"),
      entry("job", "inside"),
      entry("tub", "inside"),
    ],
  },
  d: {
    risk: "safe",
    words: [
      entry("dad", "initial"),
      entry("dog", "initial"),
      entry("day", "initial"),
      entry("door", "initial"),
      entry("duck", "initial"),
      entry("desk", "initial"),
      entry("doll", "initial"),
      entry("drink", "initial"),
      entry("dance", "initial"),
      entry("down", "initial"),
      entry("dinner", "initial"),
      entry("dark", "initial"),
      entry("dish", "initial"),
      entry("dream", "initial"),
      entry("Dan", "initial"),
      entry("red", "inside"),
      entry("bed", "inside"),
      entry("food", "inside"),
      entry("read", "inside"),
      entry("bird", "inside"),
    ],
  },
  f: {
    risk: "safe",
    words: [
      entry("fish", "initial"),
      entry("fun", "initial"),
      entry("fan", "initial"),
      entry("food", "initial"),
      entry("foot", "initial"),
      entry("five", "initial"),
      entry("family", "initial"),
      entry("friend", "initial"),
      entry("face", "initial"),
      entry("farm", "initial"),
      entry("fast", "initial"),
      entry("fine", "initial"),
      entry("frog", "initial"),
      entry("fruit", "initial"),
      entry("floor", "initial"),
      entry("off", "inside"),
      entry("leaf", "inside"),
      entry("soft", "inside"),
      entry("after", "inside"),
      entry("breakfast", "inside"),
    ],
  },
  g: {
    risk: "sensitive",
    notes: "Use hard g as in go/game. Avoid soft g words such as giant, gym and giraffe.",
    words: [
      entry("go", "initial"),
      entry("good", "initial"),
      entry("girl", "initial"),
      entry("game", "initial"),
      entry("green", "initial"),
      entry("gate", "initial"),
      entry("gift", "initial"),
      entry("glass", "initial"),
      entry("goat", "initial"),
      entry("garden", "initial"),
      entry("gold", "initial"),
      entry("gray", "initial"),
      entry("grape", "initial"),
      entry("gum", "initial"),
      entry("Grace", "initial"),
      entry("bag", "inside"),
      entry("dog", "inside"),
      entry("egg", "inside"),
      entry("frog", "inside"),
      entry("leg", "inside"),
    ],
  },
  k: {
    risk: "sensitive",
    notes: "Use common k words. Keep c/ck spelling for separate work.",
    words: [
      entry("key", "initial"),
      entry("kid", "initial"),
      entry("kite", "initial"),
      entry("kind", "initial"),
      entry("kiss", "initial"),
      entry("kitchen", "initial"),
      entry("keep", "initial"),
      entry("king", "initial"),
      entry("kick", "initial"),
      entry("Kim", "initial"),
      entry("kit", "initial"),
      entry("Kara", "initial"),
      entry("kettle", "initial"),
      entry("keyboard", "initial"),
      entry("book", "inside"),
      entry("milk", "inside"),
      entry("desk", "inside"),
      entry("bike", "inside"),
      entry("park", "inside"),
    ],
  },
  n: {
    risk: "safe",
    words: [
      entry("no", "initial"),
      entry("now", "initial"),
      entry("new", "initial"),
      entry("nine", "initial"),
      entry("name", "initial"),
      entry("nose", "initial"),
      entry("night", "initial"),
      entry("near", "initial"),
      entry("nice", "initial"),
      entry("not", "initial"),
      entry("need", "initial"),
      entry("Nina", "initial"),
      entry("north", "initial"),
      entry("one", "initial"),
      entry("sun", "inside"),
      entry("pen", "inside"),
      entry("fun", "inside"),
      entry("green", "inside"),
      entry("rain", "inside"),
      entry("window", "inside"),
      entry("dinner", "inside"),
      entry("morning", "inside"),
      entry("run", "inside"),
      entry("nest", "initial", "extra"),
      entry("nut", "initial", "extra"),
      entry("man", "inside", "extra"),
    ],
  },
  p: {
    risk: "safe",
    words: [
      entry("pen", "initial"),
      entry("pig", "initial"),
      entry("park", "initial"),
      entry("pan", "initial"),
      entry("pet", "initial"),
      entry("pot", "initial"),
      entry("pink", "initial"),
      entry("play", "initial"),
      entry("please", "initial"),
      entry("pencil", "initial"),
      entry("paper", "initial"),
      entry("pizza", "initial"),
      entry("piano", "initial"),
      entry("party", "initial"),
      entry("cup", "inside"),
      entry("apple", "inside"),
      entry("happy", "inside"),
      entry("open", "inside"),
      entry("sleep", "inside"),
    ],
  },
  t: {
    risk: "safe",
    words: [
      entry("top", "initial"),
      entry("ten", "initial"),
      entry("table", "initial"),
      entry("toy", "initial"),
      entry("tea", "initial"),
      entry("two", "initial"),
      entry("tree", "initial"),
      entry("tall", "initial"),
      entry("take", "initial"),
      entry("talk", "initial"),
      entry("time", "initial"),
      entry("Tom", "initial"),
      entry("tiger", "initial"),
      entry("teacher", "initial"),
      entry("cat", "inside"),
      entry("hat", "inside"),
      entry("water", "inside"),
      entry("little", "inside"),
      entry("night", "inside"),
    ],
  },
  v: {
    risk: "safe",
    words: [
      entry("van", "initial"),
      entry("vet", "initial"),
      entry("very", "initial"),
      entry("vest", "initial"),
      entry("visit", "initial"),
      entry("voice", "initial"),
      entry("vase", "initial"),
      entry("video", "initial"),
      entry("violin", "initial"),
      entry("Vera", "initial"),
      entry("five", "inside"),
      entry("seven", "inside"),
      entry("over", "inside"),
      entry("have", "inside"),
      entry("give", "inside"),
      entry("love", "inside"),
      entry("river", "inside"),
      entry("never", "inside"),
    ],
  },
  l: {
    risk: "safe",
    words: [
      entry("leg", "initial"),
      entry("lamp", "initial"),
      entry("lake", "initial"),
      entry("leaf", "initial"),
      entry("lemon", "initial"),
      entry("lion", "initial"),
      entry("little", "initial"),
      entry("look", "initial"),
      entry("love", "initial"),
      entry("lunch", "initial"),
      entry("Lily", "initial"),
      entry("ball", "inside"),
      entry("milk", "inside"),
      entry("blue", "inside"),
      entry("school", "inside"),
      entry("table", "inside"),
      entry("apple", "inside"),
    ],
  },
  r: {
    risk: "safe",
    words: [
      entry("red", "initial"),
      entry("run", "initial"),
      entry("rain", "initial"),
      entry("read", "initial"),
      entry("room", "initial"),
      entry("road", "initial"),
      entry("rice", "initial"),
      entry("rabbit", "initial"),
      entry("river", "initial"),
      entry("right", "initial"),
      entry("Rose", "initial"),
      entry("car", "inside"),
      entry("bird", "inside"),
      entry("green", "inside"),
      entry("bread", "inside"),
      entry("friend", "inside"),
      entry("story", "inside"),
    ],
  },
  h: {
    risk: "sensitive",
    notes: "Use pronounced h words. Avoid silent h words such as hour and honest.",
    words: [
      entry("hat", "initial"),
      entry("house", "initial"),
      entry("home", "initial"),
      entry("happy", "initial"),
      entry("hot", "initial"),
      entry("hand", "initial"),
      entry("help", "initial"),
      entry("horse", "initial"),
      entry("head", "initial"),
      entry("hill", "initial"),
      entry("hello", "initial"),
      entry("hungry", "initial"),
      entry("behind", "inside"),
      entry("ahead", "inside"),
    ],
  },
  w: {
    risk: "sensitive",
    notes: "Use pronounced w words. Keep wh for separate work.",
    words: [
      entry("we", "initial"),
      entry("water", "initial"),
      entry("walk", "initial"),
      entry("wall", "initial"),
      entry("window", "initial"),
      entry("wet", "initial"),
      entry("win", "initial"),
      entry("wish", "initial"),
      entry("wood", "initial"),
      entry("woman", "initial"),
      entry("work", "initial"),
      entry("white", "initial"),
      entry("swim", "inside"),
      entry("away", "inside"),
      entry("always", "inside"),
    ],
  },
  y: {
    risk: "sensitive",
    notes: "Use consonant y as in yes/you. Keep vowel y words for later.",
    words: [
      entry("yes", "initial"),
      entry("you", "initial"),
      entry("yellow", "initial"),
      entry("yard", "initial"),
      entry("young", "initial"),
      entry("yogurt", "initial"),
      entry("yesterday", "initial"),
      entry("year", "initial"),
      entry("your", "initial"),
      entry("yet", "initial"),
      entry("Yara", "initial"),
      entry("yo-yo", "initial"),
      entry("yummy", "initial"),
    ],
  },
  sh: {
    risk: "sensitive",
    notes: "Use sh spellings and a few common inside/final sh words.",
    words: [
      entry("she", "initial"),
      entry("ship", "initial"),
      entry("shop", "initial"),
      entry("shoe", "initial"),
      entry("shy", "initial"),
      entry("shell", "initial"),
      entry("shirt", "initial"),
      entry("short", "initial"),
      entry("shut", "initial"),
      entry("shape", "initial"),
      entry("share", "initial"),
      entry("fish", "inside"),
      entry("dish", "inside"),
      entry("wash", "inside"),
      entry("wish", "inside"),
    ],
  },
  ch: {
    risk: "sensitive",
    notes: "Use ch as in chair/chip. Avoid ch words with /k/ or /sh/ such as school, Christmas and chef.",
    words: [
      entry("chair", "initial"),
      entry("chip", "initial"),
      entry("child", "initial"),
      entry("cheese", "initial"),
      entry("chicken", "initial"),
      entry("chocolate", "initial"),
      entry("chalk", "initial"),
      entry("chase", "initial"),
      entry("choose", "initial"),
      entry("lunch", "inside"),
      entry("teacher", "inside"),
      entry("kitchen", "inside"),
      entry("watch", "inside"),
      entry("beach", "inside"),
    ],
  },
  th: {
    risk: "sensitive",
    notes: "Use common th words. Both voiced and unvoiced th are accepted in this first bank.",
    words: [
      entry("the", "initial"),
      entry("this", "initial"),
      entry("that", "initial"),
      entry("then", "initial"),
      entry("they", "initial"),
      entry("them", "initial"),
      entry("there", "initial"),
      entry("three", "initial"),
      entry("thin", "initial"),
      entry("thank", "initial"),
      entry("thing", "initial"),
      entry("mother", "inside"),
      entry("father", "inside"),
      entry("brother", "inside"),
      entry("with", "inside"),
    ],
  },
  wh: {
    risk: "sensitive",
    notes: "Use common wh question words and avoid silent-wh words or advanced spellings.",
    words: [
      entry("what", "initial"),
      entry("when", "initial"),
      entry("where", "initial"),
      entry("why", "initial"),
      entry("which", "initial"),
      entry("white", "initial"),
      entry("wheel", "initial"),
      entry("whale", "initial"),
      entry("while", "initial"),
      entry("whisper", "initial"),
      entry("who", "initial"),
    ],
  },
  j: {
    risk: "safe",
    words: [
      entry("jump", "initial"),
      entry("jam", "initial"),
      entry("jacket", "initial"),
      entry("job", "initial"),
      entry("July", "initial"),
      entry("joke", "initial"),
      entry("jeans", "initial"),
      entry("juice", "initial"),
      entry("jungle", "initial"),
      entry("Jack", "initial"),
      entry("enjoy", "inside"),
    ],
  },
  z: {
    risk: "sensitive",
    notes: "Use common z-sound words. Keep s-spelled /z/ words limited and obvious.",
    words: [
      entry("zoo", "initial"),
      entry("zebra", "initial"),
      entry("zero", "initial"),
      entry("zip", "initial"),
      entry("zipper", "initial"),
      entry("zoom", "initial"),
      entry("Zack", "initial"),
      entry("lizard", "inside"),
      entry("puzzle", "inside"),
      entry("busy", "inside"),
      entry("lazy", "inside"),
      entry("crazy", "inside"),
    ],
  },
  "hard c / k": {
    risk: "sensitive",
    notes: "Use hard c as /k/ in cat/cup/cake. Avoid soft c words such as city and pencil.",
    words: [
      entry("cat", "initial"),
      entry("cup", "initial"),
      entry("car", "initial"),
      entry("cake", "initial"),
      entry("cow", "initial"),
      entry("coat", "initial"),
      entry("corn", "initial"),
      entry("cold", "initial"),
      entry("class", "initial"),
      entry("clean", "initial"),
      entry("clock", "initial"),
      entry("cloud", "initial"),
      entry("candy", "initial"),
      entry("can", "initial"),
      entry("school", "inside"),
      entry("picnic", "inside"),
    ],
  },
  "soft c / s": {
    risk: "sensitive",
    notes: "Use soft c as /s/ before e, i or y. Avoid hard c words such as cat and cup.",
    words: [
      entry("city", "initial"),
      entry("circle", "initial"),
      entry("center", "initial"),
      entry("cereal", "initial"),
      entry("pencil", "inside"),
      entry("dance", "inside"),
      entry("face", "inside"),
      entry("ice", "inside"),
      entry("rice", "inside"),
      entry("juice", "inside"),
      entry("bicycle", "inside"),
      entry("nice", "inside"),
    ],
  },
  qu: {
    risk: "sensitive",
    notes: "Use common qu words with the /kw/ sound.",
    words: [
      entry("queen", "initial"),
      entry("quick", "initial"),
      entry("quiet", "initial"),
      entry("quilt", "initial"),
      entry("question", "initial"),
      entry("quiz", "initial"),
      entry("quite", "initial"),
      entry("quarter", "initial"),
      entry("square", "inside"),
      entry("squirrel", "inside"),
    ],
  },
  ck: {
    risk: "sensitive",
    notes: "Use common words with ck. The ck spelling usually comes later in the word.",
    words: [
      entry("duck", "inside"),
      entry("sock", "inside"),
      entry("back", "inside"),
      entry("neck", "inside"),
      entry("clock", "inside"),
      entry("black", "inside"),
      entry("truck", "inside"),
      entry("snack", "inside"),
      entry("stick", "inside"),
      entry("rock", "inside"),
      entry("lock", "inside"),
      entry("pick", "inside"),
    ],
  },
};

export const PORTUGUESE_SOUND_WORD_BANKS: Record<string, SoundWordBank> = {
  a: {
    risk: "safe",
    notes: "Use common oral a words. Keep nasal ã/an/am for a later bank.",
    words: [
      entry("água", "initial"),
      entry("amigo", "initial"),
      entry("amiga", "initial"),
      entry("ano", "initial"),
      entry("aula", "initial"),
      entry("ave", "initial"),
      entry("alto", "initial"),
      entry("aluno", "initial"),
      entry("aluna", "initial"),
      entry("Ana", "initial"),
      entry("casa", "inside"),
      entry("cama", "inside"),
      entry("sala", "inside"),
      entry("mala", "inside"),
      entry("mapa", "inside"),
      entry("gato", "inside"),
      entry("prato", "inside"),
      entry("banana", "inside"),
      entry("janela", "inside"),
      entry("família", "inside"),
    ],
  },
  i: {
    risk: "safe",
    words: [
      entry("Ivo", "initial"),
      entry("ilha", "initial"),
      entry("igreja", "initial"),
      entry("igual", "initial"),
      entry("irmão", "initial"),
      entry("ideia", "initial"),
      entry("idade", "initial"),
      entry("imagem", "initial"),
      entry("isca", "initial"),
      entry("livro", "inside"),
      entry("menino", "inside"),
      entry("menina", "inside"),
      entry("amigo", "inside"),
      entry("família", "inside"),
      entry("bonito", "inside"),
      entry("comida", "inside"),
      entry("cadeira", "inside"),
      entry("cidade", "inside"),
      entry("sorriso", "inside"),
      entry("domingo", "inside"),
    ],
  },
  u: {
    risk: "safe",
    words: [
      entry("uva", "initial"),
      entry("um", "initial"),
      entry("uma", "initial"),
      entry("urso", "initial"),
      entry("uso", "initial"),
      entry("unha", "initial"),
      entry("último", "initial"),
      entry("suco", "inside"),
      entry("rua", "inside"),
      entry("lua", "inside"),
      entry("nuvem", "inside"),
      entry("tudo", "inside"),
      entry("mundo", "inside"),
      entry("junto", "inside"),
      entry("azul", "inside"),
      entry("fruta", "inside"),
      entry("música", "inside"),
      entry("curto", "inside"),
      entry("ajuda", "inside"),
    ],
  },
  "a nasal / ã/an/am": {
    risk: "sensitive",
    notes: "Use common nasal a words written with ã, an or am. Keep ão as its own bank.",
    words: [
      entry("mãe", "initial"),
      entry("mamãe", "initial"),
      entry("maçã", "initial"),
      entry("manhã", "initial"),
      entry("irmã", "initial"),
      entry("criança", "initial"),
      entry("dança", "initial"),
      entry("canta", "initial"),
      entry("anda", "initial"),
      entry("banana", "inside"),
      entry("cantar", "inside"),
      entry("andar", "inside"),
      entry("branco", "inside"),
      entry("grande", "inside"),
      entry("planta", "inside"),
    ],
  },
  "e nasal / en/em": {
    risk: "sensitive",
    notes: "Use common nasal e words written with em or en.",
    words: [
      entry("tem", "initial"),
      entry("bem", "initial"),
      entry("sem", "initial"),
      entry("trem", "initial"),
      entry("tempo", "initial"),
      entry("sempre", "initial"),
      entry("dentro", "inside"),
      entry("vento", "inside"),
      entry("sente", "inside"),
      entry("sentar", "inside"),
      entry("entrada", "inside"),
    ],
  },
  "i nasal / in/im": {
    risk: "sensitive",
    notes: "Use common nasal i words written with im or in.",
    words: [
      entry("sim", "initial"),
      entry("fim", "initial"),
      entry("mim", "initial"),
      entry("cinco", "initial"),
      entry("limpo", "inside"),
      entry("lindo", "inside"),
      entry("tinta", "inside"),
      entry("pintar", "inside"),
      entry("cinto", "inside"),
      entry("brincar", "inside"),
    ],
  },
  "o nasal / on/om": {
    risk: "sensitive",
    notes: "Use common nasal o words written with om or on.",
    words: [
      entry("bom", "initial"),
      entry("som", "initial"),
      entry("com", "initial"),
      entry("onde", "initial"),
      entry("ontem", "initial"),
      entry("onze", "initial"),
      entry("conta", "inside"),
      entry("contar", "inside"),
      entry("ponto", "inside"),
      entry("sombra", "inside"),
      entry("compra", "inside"),
    ],
  },
  "u nasal / um/un": {
    risk: "sensitive",
    notes: "Use common nasal u words written with um or un.",
    words: [
      entry("um", "initial"),
      entry("uma", "initial"),
      entry("mundo", "inside"),
      entry("junto", "inside"),
      entry("fundo", "inside"),
      entry("segundo", "inside"),
      entry("nenhum", "inside"),
      entry("algum", "inside"),
      entry("comum", "inside"),
      entry("assunto", "inside"),
      entry("nunca", "inside"),
      entry("unha", "inside"),
    ],
  },
  "e aberto / é": {
    risk: "sensitive",
    notes: "Use open e /é/ words. Avoid closed e and nasal e words.",
    words: [
      entry("pé", "initial"),
      entry("café", "initial"),
      entry("boné", "initial"),
      entry("jacaré", "initial"),
      entry("ela", "initial"),
      entry("festa", "initial"),
      entry("perto", "initial"),
      entry("sete", "initial"),
      entry("mel", "initial"),
      entry("céu", "initial"),
      entry("José", "initial"),
      entry("colher", "inside"),
      entry("até", "inside"),
      entry("quer", "inside"),
      entry("bela", "inside"),
      entry("janela", "inside"),
      entry("terra", "inside"),
      entry("ferro", "inside"),
      entry("fé", "initial", "extra"),
      entry("mulher", "inside", "extra"),
    ],
  },
  "e fechado / ê": {
    risk: "sensitive",
    notes: "Use closed e /ê/ words. Avoid open e and nasal e words.",
    words: [
      entry("mesa", "initial"),
      entry("dedo", "initial"),
      entry("medo", "initial"),
      entry("menos", "initial"),
      entry("cedo", "initial"),
      entry("você", "initial"),
      entry("bebê", "initial"),
      entry("preto", "initial"),
      entry("peixe", "initial"),
      entry("beijo", "initial"),
      entry("queijo", "initial"),
      entry("seis", "initial"),
      entry("três", "initial"),
      entry("meia", "initial"),
      entry("leite", "inside"),
      entry("verde", "inside"),
      entry("este", "inside"),
      entry("esse", "inside"),
      entry("ler", "inside"),
      entry("ver", "inside"),
      entry("ter", "inside"),
    ],
  },
  "o aberto / ó": {
    risk: "sensitive",
    notes: "Use open o /ó/ words. Avoid closed o and nasal o words.",
    words: [
      entry("avó", "initial"),
      entry("sol", "initial"),
      entry("hora", "initial"),
      entry("agora", "initial"),
      entry("fora", "initial"),
      entry("loja", "initial"),
      entry("nove", "initial"),
      entry("nova", "initial"),
      entry("nossa", "initial"),
      entry("forte", "initial"),
      entry("posso", "initial"),
      entry("gosto", "initial"),
      entry("roda", "initial"),
      entry("olha", "initial"),
      entry("porco", "initial"),
      entry("porta", "inside"),
      entry("bola", "inside"),
      entry("escola", "inside"),
      entry("sacola", "inside"),
      entry("história", "inside"),
      entry("próximo", "inside"),
      entry("ótimo", "inside"),
      entry("volta", "inside"),
    ],
  },
  "o fechado / ô": {
    risk: "sensitive",
    notes: "Use closed o /ô/ words. Avoid open o and nasal o words.",
    words: [
      entry("ovo", "initial"),
      entry("olho", "initial"),
      entry("avô", "initial"),
      entry("boca", "initial"),
      entry("sopa", "initial"),
      entry("fogo", "initial"),
      entry("rosto", "initial"),
      entry("pouco", "initial"),
      entry("todo", "initial"),
      entry("gordo", "initial"),
      entry("coroa", "initial"),
      entry("voa", "initial"),
      entry("bolo", "inside"),
      entry("novo", "inside"),
      entry("doce", "inside"),
    ],
  },
  m: {
    risk: "sensitive",
    words: [
      entry("mãe", "initial"),
      entry("mala", "initial"),
      entry("mesa", "initial"),
      entry("meu", "initial"),
      entry("muito", "initial"),
      entry("menino", "initial"),
      entry("menina", "initial"),
      entry("morar", "initial"),
      entry("maçã", "initial"),
      entry("música", "initial"),
      entry("mercado", "initial"),
      entry("mamãe", "initial"),
      entry("mapa", "initial"),
      entry("moto", "initial"),
      entry("mel", "initial"),
      entry("medo", "initial"),
      entry("menos", "initial"),
      entry("comer", "inside"),
      entry("cama", "inside"),
      entry("amigo", "inside"),
      entry("família", "inside"),
      entry("tomate", "inside"),
      entry("nome", "inside"),
      entry("soma", "inside"),
      entry("mundo", "inside"),
      entry("domingo", "inside"),
    ],
  },
  s: {
    risk: "sensitive",
    notes: "Use clear /s/ words. Avoid intervocalic s words such as casa for now.",
    words: [
      entry("sol", "initial"),
      entry("sapo", "initial"),
      entry("sala", "initial"),
      entry("saco", "initial"),
      entry("suco", "initial"),
      entry("sopa", "initial"),
      entry("sono", "initial"),
      entry("sete", "initial"),
      entry("seis", "initial"),
      entry("sábado", "initial"),
      entry("sapato", "initial"),
      entry("sentar", "initial"),
      entry("semana", "initial"),
      entry("sempre", "initial"),
      entry("pessoa", "inside"),
      entry("massa", "inside"),
      entry("assim", "inside"),
      entry("passar", "inside"),
      entry("pássaro", "inside"),
      entry("classe", "inside"),
      entry("professor", "inside"),
      entry("salsicha", "inside"),
      entry("descer", "inside"),
      entry("nascer", "inside"),
    ],
  },
  l: {
    risk: "sensitive",
    notes: "Keep plain l separate from lh practice.",
    words: [
      entry("lua", "initial"),
      entry("lata", "initial"),
      entry("leite", "initial"),
      entry("livro", "initial"),
      entry("lápis", "initial"),
      entry("loja", "initial"),
      entry("lobo", "initial"),
      entry("lindo", "initial"),
      entry("ler", "initial"),
      entry("luz", "initial"),
      entry("lugar", "initial"),
      entry("laranja", "initial"),
      entry("limão", "initial"),
      entry("lago", "initial"),
      entry("aluno", "inside"),
      entry("aluna", "inside"),
      entry("bola", "inside"),
      entry("bolo", "inside"),
      entry("escola", "inside"),
      entry("família", "inside"),
      entry("sala", "inside"),
      entry("feliz", "inside"),
      entry("azul", "inside"),
      entry("calmo", "inside"),
    ],
  },
  b: {
    risk: "sensitive",
    words: [
      entry("bola", "initial"),
      entry("boca", "initial"),
      entry("bolo", "initial"),
      entry("bebê", "initial"),
      entry("bala", "initial"),
      entry("bonito", "initial"),
      entry("barco", "initial"),
      entry("banana", "initial"),
      entry("branco", "initial"),
      entry("baixo", "initial"),
      entry("banco", "initial"),
      entry("beber", "initial"),
      entry("brincar", "initial"),
      entry("bairro", "initial"),
      entry("cabeça", "inside"),
      entry("trabalho", "inside"),
      entry("sábado", "inside"),
      entry("abacate", "inside"),
      entry("subir", "inside"),
      entry("saber", "inside"),
      entry("robô", "inside"),
    ],
  },
  d: {
    risk: "sensitive",
    words: [
      entry("dado", "initial"),
      entry("dedo", "initial"),
      entry("dente", "initial"),
      entry("doce", "initial"),
      entry("dormir", "initial"),
      entry("dançar", "initial"),
      entry("dizer", "initial"),
      entry("dentro", "initial"),
      entry("duro", "initial"),
      entry("duas", "initial"),
      entry("dona", "initial"),
      entry("devagar", "initial"),
      entry("domingo", "initial"),
      entry("idade", "inside"),
      entry("cidade", "inside"),
      entry("comida", "inside"),
      entry("cadeira", "inside"),
      entry("ajuda", "inside"),
      entry("estudar", "inside"),
      entry("andar", "inside"),
      entry("verdade", "inside"),
    ],
  },
  f: {
    risk: "sensitive",
    words: [
      entry("faca", "initial"),
      entry("foca", "initial"),
      entry("festa", "initial"),
      entry("foto", "initial"),
      entry("fogo", "initial"),
      entry("falar", "initial"),
      entry("filho", "initial"),
      entry("filha", "initial"),
      entry("fruta", "initial"),
      entry("frio", "initial"),
      entry("feliz", "initial"),
      entry("fazer", "initial"),
      entry("fino", "initial"),
      entry("forte", "initial"),
      entry("família", "initial"),
      entry("café", "inside"),
      entry("sofá", "inside"),
      entry("telefone", "inside"),
      entry("professor", "inside"),
      entry("professora", "inside"),
      entry("difícil", "inside"),
    ],
  },
  g: {
    risk: "sensitive",
    notes: "Use hard g words with ga, go, gu, gr or gl. Avoid ge/gi words for now.",
    words: [
      entry("gato", "initial"),
      entry("galo", "initial"),
      entry("gosto", "initial"),
      entry("gola", "initial"),
      entry("garfo", "initial"),
      entry("grande", "initial"),
      entry("garota", "initial"),
      entry("garoto", "initial"),
      entry("goiaba", "initial"),
      entry("guarda", "initial"),
      entry("guitarra", "initial"),
      entry("grupo", "initial"),
      entry("gostar", "initial"),
      entry("amigo", "inside"),
      entry("lago", "inside"),
      entry("fogo", "inside"),
      entry("lugar", "inside"),
      entry("domingo", "inside"),
      entry("agora", "inside"),
      entry("água", "inside"),
    ],
  },
  p: {
    risk: "safe",
    words: [
      entry("pato", "initial"),
      entry("pai", "initial"),
      entry("pé", "initial"),
      entry("panela", "initial"),
      entry("porta", "initial"),
      entry("prato", "initial"),
      entry("preto", "initial"),
      entry("pequeno", "initial"),
      entry("parque", "initial"),
      entry("papel", "initial"),
      entry("parede", "initial"),
      entry("pacote", "initial"),
      entry("pessoa", "initial"),
      entry("professor", "initial"),
      entry("sapo", "inside"),
      entry("copo", "inside"),
      entry("sopa", "inside"),
      entry("mapa", "inside"),
      entry("roupa", "inside"),
      entry("lápis", "inside"),
      entry("tempo", "inside"),
      entry("limpo", "inside"),
      entry("campo", "inside"),
      entry("capa", "inside"),
    ],
  },
  t: {
    risk: "safe",
    words: [
      entry("tatu", "initial"),
      entry("teto", "initial"),
      entry("tomate", "initial"),
      entry("tudo", "initial"),
      entry("todos", "initial"),
      entry("trem", "initial"),
      entry("trabalho", "initial"),
      entry("tarde", "initial"),
      entry("tempo", "initial"),
      entry("tomar", "initial"),
      entry("tocar", "initial"),
      entry("turma", "initial"),
      entry("gato", "inside"),
      entry("prato", "inside"),
      entry("foto", "inside"),
      entry("leite", "inside"),
      entry("bonito", "inside"),
      entry("carta", "inside"),
      entry("porta", "inside"),
      entry("festa", "inside"),
      entry("noite", "inside"),
      entry("estudante", "inside"),
    ],
  },
  v: {
    risk: "safe",
    words: [
      entry("vaca", "initial"),
      entry("vaso", "initial"),
      entry("vida", "initial"),
      entry("verde", "initial"),
      entry("vento", "initial"),
      entry("vestido", "initial"),
      entry("viajar", "initial"),
      entry("voltar", "initial"),
      entry("você", "initial"),
      entry("vai", "initial"),
      entry("vejo", "initial"),
      entry("vivo", "initial"),
      entry("uva", "inside"),
      entry("livro", "inside"),
      entry("novo", "inside"),
      entry("cavalo", "inside"),
      entry("avião", "inside"),
      entry("jovem", "inside"),
      entry("palavra", "inside"),
      entry("favor", "inside"),
    ],
  },
  z: {
    risk: "sensitive",
    notes: "Use common Brazilian Portuguese /z/ sound words, including written z and clear intervocalic s words.",
    words: [
      entry("zero", "initial"),
      entry("zebra", "initial"),
      entry("zíper", "initial"),
      entry("Zeca", "initial"),
      entry("zangado", "initial"),
      entry("zoológico", "initial"),
      entry("casa", "inside"),
      entry("mesa", "inside"),
      entry("rosa", "inside"),
      entry("camisa", "inside"),
      entry("cozinha", "inside"),
      entry("azul", "inside"),
      entry("doze", "inside"),
      entry("onze", "inside"),
      entry("tesoura", "inside"),
    ],
  },
  c: {
    risk: "sensitive",
    notes: "Use hard c with ca, co and cu. Avoid ce/ci, ç, ch and qu words.",
    words: [
      entry("casa", "initial"),
      entry("cama", "initial"),
      entry("copo", "initial"),
      entry("comida", "initial"),
      entry("café", "initial"),
      entry("caderno", "initial"),
      entry("cadeira", "initial"),
      entry("camisa", "initial"),
      entry("carne", "initial"),
      entry("cor", "initial"),
      entry("corpo", "initial"),
      entry("curto", "initial"),
      entry("macaco", "inside"),
      entry("sacola", "inside"),
      entry("escola", "inside"),
      entry("brincar", "inside"),
      entry("faca", "inside"),
      entry("boca", "inside"),
      entry("pouco", "inside"),
      entry("rico", "inside"),
      entry("suco", "inside"),
      entry("tocar", "inside"),
    ],
  },
  qu: {
    risk: "sensitive",
    notes: "Use common que/qui words for the /k/ sound written qu.",
    words: [
      entry("queijo", "initial"),
      entry("quente", "initial"),
      entry("quarto", "initial"),
      entry("quatro", "initial"),
      entry("quintal", "initial"),
      entry("quilo", "initial"),
      entry("quieto", "initial"),
      entry("querer", "initial"),
      entry("quebrar", "initial"),
      entry("quase", "initial"),
      entry("aqui", "inside"),
      entry("pequeno", "inside"),
      entry("esquilo", "inside"),
      entry("máquina", "inside"),
      entry("parque", "inside"),
      entry("brinquedo", "inside"),
      entry("piquenique", "inside"),
    ],
  },
  gu: {
    risk: "sensitive",
    notes: "Use common hard gu words and avoid confusing ge/gi spellings.",
    words: [
      entry("guarda", "initial"),
      entry("guitarra", "initial"),
      entry("guia", "initial"),
      entry("guerra", "initial"),
      entry("agulha", "inside"),
      entry("água", "inside"),
      entry("amigo", "inside"),
      entry("foguete", "inside"),
      entry("joguete", "inside", "extra"),
      entry("língua", "inside"),
      entry("ninguém", "inside"),
      entry("salgueiro", "inside", "extra"),
    ],
  },
  r: {
    risk: "sensitive",
    notes: "Use soft/simple r between vowels or in consonant clusters. Keep initial r words for rr/strong-r practice.",
    words: [
      entry("prato", "initial"),
      entry("fruta", "initial"),
      entry("branco", "initial"),
      entry("brincar", "initial"),
      entry("professor", "initial"),
      entry("preto", "initial"),
      entry("primeiro", "initial"),
      entry("livro", "inside"),
      entry("barco", "inside"),
      entry("porta", "inside"),
      entry("verde", "inside"),
      entry("caro", "inside"),
      entry("barato", "inside"),
      entry("cadeira", "inside"),
      entry("parede", "inside"),
      entry("mercado", "inside"),
      entry("amarelo", "inside"),
    ],
  },
  rr: {
    risk: "sensitive",
    notes: "Use words written with rr and common words that start with strong r.",
    words: [
      entry("rato", "initial"),
      entry("rua", "initial"),
      entry("roupa", "initial"),
      entry("roda", "initial"),
      entry("rei", "initial"),
      entry("rosa", "initial"),
      entry("rio", "initial"),
      entry("rádio", "initial"),
      entry("carro", "initial"),
      entry("cachorro", "initial"),
      entry("garrafa", "initial"),
      entry("barriga", "initial"),
      entry("terra", "initial"),
      entry("corre", "initial"),
      entry("morro", "initial"),
      entry("ferro", "initial"),
      entry("arroz", "inside"),
      entry("macarrão", "inside"),
      entry("sorriso", "inside"),
      entry("corrida", "inside"),
      entry("bairro", "inside"),
    ],
  },
  ç: {
    risk: "sensitive",
    notes: "Use words with ç for clear /s/ spelling practice.",
    words: [
      entry("maçã", "initial"),
      entry("açúcar", "initial"),
      entry("cabeça", "initial"),
      entry("praça", "initial"),
      entry("peça", "initial"),
      entry("pedaço", "initial"),
      entry("calça", "inside"),
      entry("dança", "inside"),
      entry("canção", "inside"),
      entry("lição", "inside"),
      entry("atenção", "inside"),
      entry("coração", "inside"),
      entry("refeição", "inside"),
      entry("laço", "inside", "extra"),
      entry("moço", "inside", "extra"),
      entry("moça", "inside", "extra"),
      entry("taça", "inside", "extra"),
    ],
  },
  j: {
    risk: "sensitive",
    words: [
      entry("janela", "initial"),
      entry("jogo", "initial"),
      entry("jogar", "initial"),
      entry("jantar", "initial"),
      entry("jardim", "initial"),
      entry("jaqueta", "initial"),
      entry("joelho", "initial"),
      entry("jovem", "initial"),
      entry("junto", "initial"),
      entry("junho", "initial"),
      entry("feijão", "inside"),
      entry("beijo", "inside"),
      entry("loja", "inside"),
      entry("sujo", "inside"),
      entry("laranja", "inside"),
      entry("viajar", "inside"),
    ],
  },
  x: {
    risk: "sensitive",
    notes: "Use only common x words with a stable sh-like sound for now.",
    words: [
      entry("xícara", "initial"),
      entry("xadrez", "initial"),
      entry("peixe", "inside"),
      entry("caixa", "inside"),
      entry("baixo", "inside"),
      entry("deixar", "inside"),
      entry("lixo", "inside"),
      entry("mexer", "inside"),
      entry("roxo", "inside"),
      entry("ameixa", "inside"),
      entry("faixa", "inside"),
      entry("xarope", "initial", "extra"),
      entry("xampu", "initial", "extra"),
      entry("xale", "initial", "extra"),
    ],
  },
  n: {
    risk: "sensitive",
    notes: "Keep plain n separate from nh practice.",
    words: [
      entry("neto", "initial"),
      entry("nada", "initial"),
      entry("nove", "initial"),
      entry("novo", "initial"),
      entry("nome", "initial"),
      entry("noite", "initial"),
      entry("nariz", "initial"),
      entry("nuvem", "initial"),
      entry("nadar", "initial"),
      entry("Nina", "initial"),
      entry("nossa", "initial"),
      entry("nunca", "initial"),
      entry("nota", "initial"),
      entry("norte", "initial"),
      entry("menino", "inside"),
      entry("menina", "inside"),
      entry("banana", "inside"),
      entry("janela", "inside"),
      entry("caneta", "inside"),
      entry("panela", "inside"),
      entry("boneca", "inside"),
      entry("telefone", "inside"),
      entry("pequeno", "inside"),
      entry("bonito", "inside"),
      entry("cantar", "inside"),
      entry("dançar", "inside"),
      entry("ensinar", "inside"),
      entry("brincar", "inside"),
    ],
  },
  nh: {
    risk: "sensitive",
    notes: "The Brazilian Portuguese nh sound is usually written nh and rarely starts a word.",
    words: [
      entry("ninho", "initial"),
      entry("minha", "initial"),
      entry("manhã", "initial"),
      entry("banho", "initial"),
      entry("sonho", "initial"),
      entry("tenho", "initial"),
      entry("venha", "initial"),
      entry("unha", "initial"),
      entry("cozinha", "inside"),
      entry("galinha", "inside"),
      entry("caminho", "inside"),
      entry("sozinho", "inside"),
      entry("desenho", "inside"),
      entry("carinho", "inside"),
      entry("dinheiro", "inside"),
      entry("vizinho", "inside"),
      entry("sobrinha", "inside"),
      entry("sobrinho", "inside"),
      entry("companhia", "inside", "extra"),
      entry("linha", "inside", "extra"),
    ],
  },
  lh: {
    risk: "sensitive",
    notes: "The Brazilian Portuguese lh sound is written lh and rarely starts a word.",
    words: [
      entry("olho", "initial"),
      entry("filho", "initial"),
      entry("filha", "initial"),
      entry("milho", "initial"),
      entry("folha", "initial"),
      entry("molho", "initial"),
      entry("velho", "initial"),
      entry("toalha", "initial"),
      entry("abelha", "inside"),
      entry("ilha", "inside"),
      entry("trabalho", "inside"),
      entry("barulho", "inside"),
      entry("agulha", "inside"),
      entry("colher", "inside"),
      entry("melhor", "inside"),
      entry("molhado", "inside"),
      entry("vermelho", "inside"),
      entry("espelho", "inside"),
      entry("bilhete", "inside", "extra"),
      entry("alho", "inside", "extra"),
    ],
  },
  ch: {
    risk: "sensitive",
    notes: "For Brazilian Portuguese ch, use words written with ch and avoid mixing with x words for now.",
    words: [
      entry("chá", "initial"),
      entry("chave", "initial"),
      entry("chuva", "initial"),
      entry("chão", "initial"),
      entry("chapéu", "initial"),
      entry("chefe", "initial"),
      entry("cheio", "initial"),
      entry("chegar", "initial"),
      entry("chamar", "initial"),
      entry("fechar", "initial"),
      entry("chorar", "initial"),
      entry("chutar", "initial"),
      entry("chocolate", "initial"),
      entry("mochila", "inside"),
      entry("lanche", "inside"),
      entry("cachorro", "inside"),
      entry("bolacha", "inside"),
      entry("fechado", "inside"),
      entry("machucado", "inside"),
      entry("fichário", "inside", "extra"),
      entry("bicho", "inside", "extra"),
    ],
  },
  "ão": {
    risk: "sensitive",
    notes: "Use common Brazilian Portuguese words with the nasal ão ending.",
    words: [
      entry("pão", "initial"),
      entry("mão", "initial"),
      entry("chão", "initial"),
      entry("cão", "initial"),
      entry("irmão", "initial"),
      entry("mamão", "initial"),
      entry("limão", "initial"),
      entry("fogão", "initial"),
      entry("balão", "inside"),
      entry("coração", "inside"),
      entry("avião", "inside"),
      entry("lição", "inside"),
      entry("canção", "inside"),
      entry("atenção", "inside"),
      entry("refeição", "inside"),
      entry("estação", "inside"),
      entry("televisão", "inside"),
      entry("informação", "inside"),
      entry("brincalhão", "inside", "extra"),
      entry("caminhão", "inside", "extra"),
    ],
  },
};

function normalizeSound(value: string): string {
  return value.trim().toLocaleLowerCase();
}

function normalizeWord(value: string): string {
  return value.trim().toLocaleLowerCase();
}

export function getNorwegianSoundWordEntries(sound: string): SoundWordEntry[] {
  return NORWEGIAN_SOUND_WORD_BANKS[normalizeSound(sound)]?.words ?? [];
}

export function getNorwegianSoundWords(sound: string, count: number): string[] {
  if (count <= 0) return [];
  const entries = getNorwegianSoundWordEntries(sound);
  return entries.slice(0, count).map((item) => item.word);
}

export function getNorwegianInsideSoundWords(sound: string): string[] {
  return getNorwegianSoundWordEntries(sound)
    .filter((item) => item.position === "inside")
    .map((item) => item.word);
}

export function isApprovedNorwegianSoundWord(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  return getNorwegianSoundWordEntries(sound).some((item) => normalizeWord(item.word) === normalizedWord);
}

export function norwegianSoundWordStartsWithSound(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  const normalizedSound = normalizeSound(sound);
  const entry = getNorwegianSoundWordEntries(sound).find((item) => normalizeWord(item.word) === normalizedWord);
  if (entry) return entry.position === "initial";
  return normalizedWord.startsWith(normalizedSound);
}

export function norwegianSoundWordContainsSound(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  const normalizedSound = normalizeSound(sound);
  return isApprovedNorwegianSoundWord(sound, word) || normalizedWord.includes(normalizedSound);
}

export function getNorwegianSoundBank(sound: string): SoundWordBank | null {
  return NORWEGIAN_SOUND_WORD_BANKS[normalizeSound(sound)] ?? null;
}

export function getEnglishSoundWordEntries(sound: string): SoundWordEntry[] {
  return ENGLISH_SOUND_WORD_BANKS[normalizeSound(sound)]?.words ?? [];
}

export function getEnglishSoundWords(sound: string, count: number): string[] {
  if (count <= 0) return [];
  const entries = getEnglishSoundWordEntries(sound);
  return entries.slice(0, count).map((item) => item.word);
}

export function getEnglishInsideSoundWords(sound: string): string[] {
  return getEnglishSoundWordEntries(sound)
    .filter((item) => item.position === "inside")
    .map((item) => item.word);
}

export function isApprovedEnglishSoundWord(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  return getEnglishSoundWordEntries(sound).some((item) => normalizeWord(item.word) === normalizedWord);
}

export function englishSoundWordStartsWithSound(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  const normalizedSound = normalizeSound(sound);
  const entry = getEnglishSoundWordEntries(sound).find((item) => normalizeWord(item.word) === normalizedWord);
  if (entry) return entry.position === "initial";
  return normalizedWord.startsWith(normalizedSound);
}

export function englishSoundWordContainsSound(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  const normalizedSound = normalizeSound(sound);
  return isApprovedEnglishSoundWord(sound, word) || normalizedWord.includes(normalizedSound);
}

export function getEnglishSoundBank(sound: string): SoundWordBank | null {
  return ENGLISH_SOUND_WORD_BANKS[normalizeSound(sound)] ?? null;
}

export function getPortugueseSoundWordEntries(sound: string): SoundWordEntry[] {
  return PORTUGUESE_SOUND_WORD_BANKS[normalizeSound(sound)]?.words ?? [];
}

export function getPortugueseSoundWords(sound: string, count: number): string[] {
  if (count <= 0) return [];
  const entries = getPortugueseSoundWordEntries(sound);
  return entries.slice(0, count).map((item) => item.word);
}

export function getPortugueseInsideSoundWords(sound: string): string[] {
  return getPortugueseSoundWordEntries(sound)
    .filter((item) => item.position === "inside")
    .map((item) => item.word);
}

export function isApprovedPortugueseSoundWord(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  return getPortugueseSoundWordEntries(sound).some((item) => normalizeWord(item.word) === normalizedWord);
}

export function portugueseSoundWordStartsWithSound(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  const normalizedSound = normalizeSound(sound);
  const entry = getPortugueseSoundWordEntries(sound).find((item) => normalizeWord(item.word) === normalizedWord);
  if (entry) return entry.position === "initial";
  return normalizedWord.startsWith(normalizedSound);
}

export function portugueseSoundWordContainsSound(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  const normalizedSound = normalizeSound(sound);
  return isApprovedPortugueseSoundWord(sound, word) || normalizedWord.includes(normalizedSound);
}

export function getPortugueseSoundBank(sound: string): SoundWordBank | null {
  return PORTUGUESE_SOUND_WORD_BANKS[normalizeSound(sound)] ?? null;
}
