export type SoundWordPosition = "initial" | "inside";
export type SoundWordLevel = "core" | "extra";
export type SoundRisk = "safe" | "sensitive";

export type SoundWordEntry = {
  word: string;
  position: SoundWordPosition;
  level: SoundWordLevel;
};

export type SoundWordBank = {
  risk: SoundRisk;
  notes?: string;
  words: SoundWordEntry[];
};

function entry(word: string, position: SoundWordPosition, level: SoundWordLevel = "core"): SoundWordEntry {
  return { word, position, level };
}

export const NORWEGIAN_SOUND_WORD_BANKS: Record<string, SoundWordBank> = {
  s: {
    risk: "safe",
    words: [
      entry("sol", "initial"),
      entry("saft", "initial"),
      entry("seng", "initial"),
      entry("sekk", "initial"),
      entry("sko", "initial"),
      entry("suppe", "initial"),
      entry("sitte", "initial"),
      entry("se", "initial"),
      entry("si", "initial"),
      entry("sang", "initial"),
      entry("sommer", "initial"),
      entry("skole", "initial"),
      entry("stol", "initial"),
      entry("sulten", "initial"),
      entry("søt", "initial"),
      entry("buss", "inside"),
      entry("hus", "inside"),
      entry("lese", "inside"),
      entry("pose", "inside"),
      entry("danse", "inside"),
      entry("fisk", "inside"),
      entry("ost", "inside"),
      entry("klasse", "inside"),
      entry("bestemor", "inside"),
      entry("hest", "inside"),
      entry("is", "inside"),
    ],
  },
  m: {
    risk: "safe",
    words: [
      entry("mat", "initial"),
      entry("mor", "initial"),
      entry("mus", "initial"),
      entry("melk", "initial"),
      entry("mål", "initial"),
      entry("mye", "initial"),
      entry("min", "initial"),
      entry("mitt", "initial"),
      entry("måne", "initial"),
      entry("mann", "initial"),
      entry("mamma", "initial"),
      entry("morgen", "initial"),
      entry("munn", "initial"),
      entry("med", "initial"),
      entry("møter", "initial"),
      entry("rom", "inside"),
      entry("hjem", "inside"),
      entry("sommer", "inside"),
      entry("familie", "inside"),
      entry("komme", "inside"),
      entry("lampe", "inside"),
      entry("nummer", "inside"),
      entry("gammel", "inside"),
      entry("klemme", "inside"),
      entry("lomme", "inside"),
      entry("tomat", "inside"),
    ],
  },
  a: {
    risk: "safe",
    words: [
      entry("and", "initial"),
      entry("ape", "initial"),
      entry("arm", "initial"),
      entry("ark", "initial"),
      entry("alle", "initial"),
      entry("Anna", "initial"),
      entry("Ali", "initial"),
      entry("av", "initial"),
      entry("at", "initial"),
      entry("appelsin", "initial"),
      entry("arbeid", "initial"),
      entry("ansikt", "initial"),
      entry("aldri", "initial"),
      entry("alltid", "initial"),
      entry("mat", "inside"),
      entry("Sara", "inside"),
      entry("banan", "inside"),
      entry("kake", "inside"),
      entry("glad", "inside"),
      entry("dag", "inside"),
      entry("pappa", "inside"),
      entry("mamma", "inside"),
      entry("familie", "inside"),
      entry("salat", "inside"),
      entry("hatt", "inside"),
      entry("jakke", "inside"),
    ],
  },
  b: {
    risk: "safe",
    words: [
      entry("bil", "initial"),
      entry("bok", "initial"),
      entry("ball", "initial"),
      entry("bord", "initial"),
      entry("buss", "initial"),
      entry("barn", "initial"),
      entry("brød", "initial"),
      entry("båt", "initial"),
      entry("ben", "initial"),
      entry("blå", "initial"),
      entry("butikk", "initial"),
      entry("bamse", "initial"),
      entry("bade", "initial"),
      entry("bilde", "initial"),
      entry("bak", "initial"),
      entry("jobb", "inside"),
      entry("kube", "inside"),
      entry("robot", "inside"),
      entry("tabell", "inside"),
      entry("nabo", "inside"),
      entry("skrubbe", "inside", "extra"),
      entry("krabbe", "inside"),
      entry("lommebok", "inside"),
    ],
  },
  d: {
    risk: "safe",
    words: [
      entry("dag", "initial"),
      entry("du", "initial"),
      entry("din", "initial"),
      entry("dyr", "initial"),
      entry("dør", "initial"),
      entry("dans", "initial"),
      entry("dukke", "initial"),
      entry("drue", "initial"),
      entry("drikke", "initial"),
      entry("dele", "initial"),
      entry("der", "initial"),
      entry("dame", "initial"),
      entry("datter", "initial"),
      entry("data", "initial"),
      entry("dusj", "initial"),
      entry("skade", "inside"),
      entry("bilde", "inside"),
      entry("side", "inside"),
      entry("hode", "inside"),
      entry("middag", "inside"),
      entry("bade", "inside"),
      entry("nede", "inside"),
      entry("redde", "inside"),
      entry("rydde", "inside"),
      entry("lyd", "inside"),
    ],
  },
  f: {
    risk: "safe",
    words: [
      entry("far", "initial"),
      entry("fisk", "initial"),
      entry("fot", "initial"),
      entry("fin", "initial"),
      entry("fugl", "initial"),
      entry("fem", "initial"),
      entry("frokost", "initial"),
      entry("frukt", "initial"),
      entry("farge", "initial"),
      entry("får", "initial"),
      entry("familie", "initial"),
      entry("finner", "initial"),
      entry("fart", "initial"),
      entry("fryser", "initial"),
      entry("følge", "initial"),
      entry("kaffe", "inside"),
      entry("sofa", "inside"),
      entry("telefon", "inside"),
      entry("vaffel", "inside"),
      entry("skuff", "inside"),
      entry("tøff", "inside"),
      entry("loft", "inside"),
      entry("saft", "inside"),
      entry("ofte", "inside"),
      entry("lufte", "inside"),
    ],
  },
  g: {
    risk: "safe",
    words: [
      entry("gå", "initial"),
      entry("god", "initial"),
      entry("gul", "initial"),
      entry("gris", "initial"),
      entry("gutt", "initial"),
      entry("gate", "initial"),
      entry("gave", "initial"),
      entry("genser", "initial"),
      entry("glass", "initial"),
      entry("glede", "initial"),
      entry("grøt", "initial"),
      entry("grønn", "initial"),
      entry("gammel", "initial"),
      entry("gitar", "initial"),
      entry("gulrot", "initial"),
      entry("dag", "inside"),
      entry("tog", "inside"),
      entry("hage", "inside"),
      entry("mage", "inside"),
      entry("farge", "inside"),
      entry("morgen", "inside"),
      entry("legge", "inside"),
      entry("ligge", "inside"),
      entry("fugl", "inside"),
      entry("rolig", "inside"),
      entry("sag", "inside"),
    ],
  },
  k: {
    risk: "sensitive",
    notes: "Plain k should not mix with kj/skj words.",
    words: [
      entry("katt", "initial"),
      entry("kake", "initial"),
      entry("kopp", "initial"),
      entry("kul", "initial"),
      entry("kan", "initial"),
      entry("kommer", "initial"),
      entry("kald", "initial"),
      entry("kort", "initial"),
      entry("klasse", "initial"),
      entry("klokke", "initial"),
      entry("kropp", "initial"),
      entry("klem", "initial"),
      entry("kveld", "initial"),
      entry("ku", "initial"),
      entry("bok", "inside"),
      entry("tak", "inside"),
      entry("pakke", "inside"),
      entry("sokker", "inside"),
      entry("drikke", "inside"),
      entry("skole", "inside"),
      entry("voksen", "inside"),
      entry("lek", "inside"),
      entry("frokost", "inside"),
      entry("matpakke", "inside"),
      entry("jakke", "inside"),
    ],
  },
  n: {
    risk: "safe",
    words: [
      entry("natt", "initial"),
      entry("nese", "initial"),
      entry("navn", "initial"),
      entry("ni", "initial"),
      entry("ny", "initial"),
      entry("norsk", "initial"),
      entry("nøkkel", "initial"),
      entry("nabo", "initial"),
      entry("natur", "initial"),
      entry("nå", "initial"),
      entry("nær", "initial"),
      entry("ned", "initial"),
      entry("noen", "initial"),
      entry("Nina", "initial"),
      entry("notat", "initial"),
      entry("banan", "inside"),
      entry("vann", "inside"),
      entry("venn", "inside"),
      entry("mann", "inside"),
      entry("hund", "inside"),
      entry("kanin", "inside"),
      entry("måne", "inside"),
      entry("panne", "inside"),
      entry("fin", "inside"),
      entry("grønn", "inside"),
      entry("barn", "inside"),
    ],
  },
  e: {
    risk: "safe",
    words: [
      entry("egg", "initial"),
      entry("en", "initial"),
      entry("et", "initial"),
      entry("eple", "initial"),
      entry("elefant", "initial"),
      entry("elleve", "initial"),
      entry("etter", "initial"),
      entry("elev", "initial"),
      entry("egen", "initial"),
      entry("enkel", "initial"),
      entry("elsker", "initial"),
      entry("eske", "initial"),
      entry("elv", "initial"),
      entry("ende", "initial"),
      entry("er", "initial"),
      entry("se", "inside"),
      entry("leke", "inside"),
      entry("lese", "inside"),
      entry("seng", "inside"),
      entry("bestemor", "inside"),
      entry("venn", "inside"),
      entry("melk", "inside"),
      entry("hest", "inside"),
      entry("lek", "inside"),
      entry("pen", "inside"),
      entry("del", "inside"),
    ],
  },
  o: {
    risk: "safe",
    words: [
      entry("ost", "initial"),
      entry("ord", "initial"),
      entry("Ole", "initial"),
      entry("Oda", "initial"),
      entry("opp", "initial"),
      entry("onkel", "initial"),
      entry("onsdag", "initial"),
      entry("område", "initial"),
      entry("okse", "initial"),
      entry("om", "initial"),
      entry("sol", "inside"),
      entry("sko", "inside"),
      entry("bok", "inside"),
      entry("bord", "inside"),
      entry("mor", "inside"),
      entry("bror", "inside"),
      entry("pose", "inside"),
      entry("jobb", "inside"),
      entry("robot", "inside"),
      entry("foto", "inside"),
      entry("to", "inside"),
      entry("ro", "inside"),
      entry("bo", "inside"),
      entry("bor", "inside"),
      entry("stor", "inside"),
      entry("god", "inside"),
    ],
  },
  u: {
    risk: "safe",
    words: [
      entry("ut", "initial"),
      entry("ull", "initial"),
      entry("uke", "initial"),
      entry("under", "initial"),
      entry("ute", "initial"),
      entry("uten", "initial"),
      entry("ulv", "initial"),
      entry("Ulla", "initial"),
      entry("ugle", "initial"),
      entry("usikker", "initial"),
      entry("univers", "initial", "extra"),
      entry("unik", "initial", "extra"),
      entry("utstyr", "initial"),
      entry("hus", "inside"),
      entry("buss", "inside"),
      entry("suppe", "inside"),
      entry("gul", "inside"),
      entry("tur", "inside"),
      entry("hund", "inside"),
      entry("lunsj", "inside"),
      entry("frukt", "inside"),
      entry("brun", "inside"),
      entry("mus", "inside"),
      entry("du", "inside"),
    ],
  },
  æ: {
    risk: "safe",
    words: [
      entry("ærlig", "initial"),
      entry("ærend", "initial"),
      entry("her", "initial"),
      entry("der", "initial"),
      entry("er", "initial"),
      entry("bær", "inside"),
      entry("vær", "inside"),
      entry("nær", "inside"),
      entry("lærer", "inside"),
      entry("klær", "inside"),
      entry("tær", "inside"),
      entry("kjær", "inside"),
      entry("været", "inside"),
      entry("stjerne", "inside"),
      entry("sær", "inside", "extra"),
      entry("ære", "inside", "extra"),
    ],
  },
  ø: {
    risk: "safe",
    words: [
      entry("øye", "initial"),
      entry("øre", "initial"),
      entry("øy", "initial"),
      entry("øve", "initial"),
      entry("ønske", "initial"),
      entry("øse", "initial"),
      entry("søt", "inside"),
      entry("brød", "inside"),
      entry("grøt", "inside"),
      entry("følge", "inside"),
      entry("møte", "inside"),
      entry("rød", "inside"),
      entry("grønn", "inside"),
      entry("løpe", "inside"),
      entry("høre", "inside"),
      entry("bøker", "inside"),
      entry("dør", "inside"),
      entry("søster", "inside"),
      entry("høne", "inside"),
      entry("skjørt", "inside"),
      entry("kjøkken", "inside"),
      entry("kjøpe", "inside"),
    ],
  },
  å: {
    risk: "safe",
    words: [
      entry("å", "initial"),
      entry("år", "initial"),
      entry("åtte", "initial"),
      entry("ål", "initial", "extra"),
      entry("båt", "inside"),
      entry("blå", "inside"),
      entry("får", "inside"),
      entry("går", "inside"),
      entry("står", "inside"),
      entry("må", "inside"),
      entry("nå", "inside"),
      entry("så", "inside"),
      entry("på", "inside"),
      entry("låne", "inside"),
      entry("måne", "inside"),
      entry("hår", "inside"),
      entry("tå", "inside"),
      entry("våt", "inside"),
      entry("grå", "inside"),
      entry("små", "inside"),
    ],
  },
  sj: {
    risk: "sensitive",
    notes: "The Norwegian sj sound can be written sj, skj and some sk before front vowels.",
    words: [
      entry("sjakk", "initial"),
      entry("sjal", "initial"),
      entry("sjef", "initial"),
      entry("sjekk", "initial"),
      entry("sjekke", "initial"),
      entry("sjekkliste", "initial", "extra"),
      entry("sjokolade", "initial"),
      entry("sjokoladepudding", "initial", "extra"),
      entry("sjø", "initial"),
      entry("sjømann", "initial", "extra"),
      entry("sjåfør", "initial"),
      entry("sjampo", "initial"),
      entry("sjarm", "initial", "extra"),
      entry("skjegg", "initial"),
      entry("skje", "initial"),
      entry("skjell", "initial"),
      entry("skjerm", "initial"),
      entry("skjorte", "initial"),
      entry("skjørt", "initial"),
      entry("skjære", "initial"),
      entry("ski", "initial"),
      entry("skilt", "initial"),
      entry("skinke", "initial"),
      entry("skinn", "initial", "extra"),
      entry("sky", "initial"),
      entry("skygge", "initial"),
      entry("kanskje", "inside"),
      entry("maskin", "inside"),
      entry("dusje", "inside"),
      entry("garasje", "inside"),
      entry("brosjyre", "inside", "extra"),
    ],
  },
  kj: {
    risk: "sensitive",
    notes: "Keep kj separate from k and sj/skj words.",
    words: [
      entry("kjole", "initial"),
      entry("kjøkken", "initial"),
      entry("kjøtt", "initial"),
      entry("kjeks", "initial"),
      entry("kjekk", "initial"),
      entry("kjenne", "initial"),
      entry("kjøpe", "initial"),
      entry("kjøre", "initial"),
      entry("kjede", "initial"),
      entry("kjeller", "initial"),
      entry("kjølig", "initial", "extra"),
      entry("kjapp", "initial"),
      entry("Kjell", "initial"),
      entry("kjele", "initial"),
      entry("kjæledyr", "initial"),
      entry("kjøleskap", "initial"),
      entry("kjempe", "initial"),
      entry("kjempefin", "initial"),
      entry("kjent", "initial"),
      entry("kjenner", "initial"),
      entry("kjempestor", "initial", "extra"),
      entry("bikkje", "inside"),
    ],
  },
};

export const PORTUGUESE_SOUND_WORD_BANKS: Record<string, SoundWordBank> = {
  m: {
    risk: "sensitive",
    words: [
      entry("mãe", "initial"),
      entry("mala", "initial"),
      entry("mesa", "initial"),
      entry("meu", "initial"),
      entry("muito", "initial"),
      entry("menino", "initial"),
      entry("menina", "initial"),
      entry("morar", "initial"),
      entry("maçã", "initial"),
      entry("música", "initial"),
      entry("mercado", "initial"),
      entry("mamãe", "initial"),
      entry("mapa", "initial"),
      entry("moto", "initial"),
      entry("mel", "initial"),
      entry("medo", "initial"),
      entry("menos", "initial"),
      entry("comer", "inside"),
      entry("cama", "inside"),
      entry("amigo", "inside"),
      entry("família", "inside"),
      entry("tomate", "inside"),
      entry("nome", "inside"),
      entry("soma", "inside"),
      entry("mundo", "inside"),
      entry("domingo", "inside"),
    ],
  },
  s: {
    risk: "sensitive",
    notes: "Use clear /s/ words. Avoid intervocalic s words such as casa for now.",
    words: [
      entry("sol", "initial"),
      entry("sapo", "initial"),
      entry("sala", "initial"),
      entry("saco", "initial"),
      entry("suco", "initial"),
      entry("sopa", "initial"),
      entry("sono", "initial"),
      entry("sete", "initial"),
      entry("seis", "initial"),
      entry("sábado", "initial"),
      entry("sapato", "initial"),
      entry("sentar", "initial"),
      entry("semana", "initial"),
      entry("sempre", "initial"),
      entry("pessoa", "inside"),
      entry("massa", "inside"),
      entry("assim", "inside"),
      entry("passar", "inside"),
      entry("pássaro", "inside"),
      entry("classe", "inside"),
      entry("professor", "inside"),
      entry("salsicha", "inside"),
      entry("descer", "inside"),
      entry("nascer", "inside"),
    ],
  },
  l: {
    risk: "sensitive",
    notes: "Keep plain l separate from lh practice.",
    words: [
      entry("lua", "initial"),
      entry("lata", "initial"),
      entry("leite", "initial"),
      entry("livro", "initial"),
      entry("lápis", "initial"),
      entry("loja", "initial"),
      entry("lobo", "initial"),
      entry("lindo", "initial"),
      entry("ler", "initial"),
      entry("luz", "initial"),
      entry("lugar", "initial"),
      entry("laranja", "initial"),
      entry("limão", "initial"),
      entry("lago", "initial"),
      entry("aluno", "inside"),
      entry("aluna", "inside"),
      entry("bola", "inside"),
      entry("bolo", "inside"),
      entry("escola", "inside"),
      entry("família", "inside"),
      entry("sala", "inside"),
      entry("feliz", "inside"),
      entry("azul", "inside"),
      entry("calmo", "inside"),
    ],
  },
  b: {
    risk: "sensitive",
    words: [
      entry("bola", "initial"),
      entry("boca", "initial"),
      entry("bolo", "initial"),
      entry("bebê", "initial"),
      entry("bala", "initial"),
      entry("bonito", "initial"),
      entry("barco", "initial"),
      entry("banana", "initial"),
      entry("branco", "initial"),
      entry("baixo", "initial"),
      entry("banco", "initial"),
      entry("beber", "initial"),
      entry("brincar", "initial"),
      entry("bairro", "initial"),
      entry("cabeça", "inside"),
      entry("trabalho", "inside"),
      entry("sábado", "inside"),
      entry("abacate", "inside"),
      entry("subir", "inside"),
      entry("saber", "inside"),
      entry("robô", "inside"),
    ],
  },
  d: {
    risk: "sensitive",
    words: [
      entry("dado", "initial"),
      entry("dedo", "initial"),
      entry("dente", "initial"),
      entry("doce", "initial"),
      entry("dormir", "initial"),
      entry("dançar", "initial"),
      entry("dizer", "initial"),
      entry("dentro", "initial"),
      entry("duro", "initial"),
      entry("duas", "initial"),
      entry("dona", "initial"),
      entry("devagar", "initial"),
      entry("domingo", "initial"),
      entry("idade", "inside"),
      entry("cidade", "inside"),
      entry("comida", "inside"),
      entry("cadeira", "inside"),
      entry("ajuda", "inside"),
      entry("estudar", "inside"),
      entry("andar", "inside"),
      entry("verdade", "inside"),
    ],
  },
  f: {
    risk: "sensitive",
    words: [
      entry("faca", "initial"),
      entry("foca", "initial"),
      entry("festa", "initial"),
      entry("foto", "initial"),
      entry("fogo", "initial"),
      entry("falar", "initial"),
      entry("filho", "initial"),
      entry("filha", "initial"),
      entry("fruta", "initial"),
      entry("frio", "initial"),
      entry("feliz", "initial"),
      entry("fazer", "initial"),
      entry("fino", "initial"),
      entry("forte", "initial"),
      entry("família", "initial"),
      entry("café", "inside"),
      entry("sofá", "inside"),
      entry("telefone", "inside"),
      entry("professor", "inside"),
      entry("professora", "inside"),
      entry("difícil", "inside"),
    ],
  },
  g: {
    risk: "sensitive",
    notes: "Use hard g words with ga, go, gu, gr or gl. Avoid ge/gi words for now.",
    words: [
      entry("gato", "initial"),
      entry("galo", "initial"),
      entry("gosto", "initial"),
      entry("gola", "initial"),
      entry("garfo", "initial"),
      entry("grande", "initial"),
      entry("garota", "initial"),
      entry("garoto", "initial"),
      entry("goiaba", "initial"),
      entry("guarda", "initial"),
      entry("guitarra", "initial"),
      entry("grupo", "initial"),
      entry("gostar", "initial"),
      entry("amigo", "inside"),
      entry("lago", "inside"),
      entry("fogo", "inside"),
      entry("lugar", "inside"),
      entry("domingo", "inside"),
      entry("agora", "inside"),
      entry("água", "inside"),
    ],
  },
  qu: {
    risk: "sensitive",
    notes: "Use common que/qui words for the /k/ sound written qu.",
    words: [
      entry("queijo", "initial"),
      entry("quente", "initial"),
      entry("quarto", "initial"),
      entry("quatro", "initial"),
      entry("quintal", "initial"),
      entry("quilo", "initial"),
      entry("quieto", "initial"),
      entry("querer", "initial"),
      entry("quebrar", "initial"),
      entry("quase", "initial"),
      entry("aqui", "inside"),
      entry("pequeno", "inside"),
      entry("esquilo", "inside"),
      entry("máquina", "inside"),
      entry("parque", "inside"),
      entry("brinquedo", "inside"),
      entry("piquenique", "inside"),
    ],
  },
  gu: {
    risk: "sensitive",
    notes: "Use common hard gu words and avoid confusing ge/gi spellings.",
    words: [
      entry("guarda", "initial"),
      entry("guitarra", "initial"),
      entry("guia", "initial"),
      entry("guerra", "initial"),
      entry("agulha", "inside"),
      entry("água", "inside"),
      entry("amigo", "inside"),
      entry("foguete", "inside"),
      entry("joguete", "inside", "extra"),
      entry("língua", "inside"),
      entry("ninguém", "inside"),
      entry("salgueiro", "inside", "extra"),
    ],
  },
  r: {
    risk: "sensitive",
    notes: "Use soft/simple r between vowels or in consonant clusters. Keep initial r words for rr/strong-r practice.",
    words: [
      entry("prato", "initial"),
      entry("fruta", "initial"),
      entry("branco", "initial"),
      entry("brincar", "initial"),
      entry("professor", "initial"),
      entry("preto", "initial"),
      entry("primeiro", "initial"),
      entry("livro", "inside"),
      entry("barco", "inside"),
      entry("porta", "inside"),
      entry("verde", "inside"),
      entry("caro", "inside"),
      entry("barato", "inside"),
      entry("cadeira", "inside"),
      entry("parede", "inside"),
      entry("mercado", "inside"),
      entry("amarelo", "inside"),
    ],
  },
  rr: {
    risk: "sensitive",
    notes: "Use words written with rr and common words that start with strong r.",
    words: [
      entry("rato", "initial"),
      entry("rua", "initial"),
      entry("roupa", "initial"),
      entry("roda", "initial"),
      entry("rei", "initial"),
      entry("rosa", "initial"),
      entry("rio", "initial"),
      entry("rádio", "initial"),
      entry("carro", "initial"),
      entry("cachorro", "initial"),
      entry("garrafa", "initial"),
      entry("barriga", "initial"),
      entry("terra", "initial"),
      entry("corre", "initial"),
      entry("morro", "initial"),
      entry("ferro", "initial"),
      entry("arroz", "inside"),
      entry("macarrão", "inside"),
      entry("sorriso", "inside"),
      entry("corrida", "inside"),
      entry("bairro", "inside"),
    ],
  },
  ç: {
    risk: "sensitive",
    notes: "Use words with ç for clear /s/ spelling practice.",
    words: [
      entry("maçã", "initial"),
      entry("açúcar", "initial"),
      entry("cabeça", "initial"),
      entry("praça", "initial"),
      entry("peça", "initial"),
      entry("taça", "initial"),
      entry("laço", "initial"),
      entry("moço", "initial"),
      entry("moça", "initial"),
      entry("calça", "inside"),
      entry("dança", "inside"),
      entry("canção", "inside"),
      entry("lição", "inside"),
      entry("atenção", "inside"),
      entry("coração", "inside"),
      entry("refeição", "inside"),
    ],
  },
  j: {
    risk: "sensitive",
    words: [
      entry("janela", "initial"),
      entry("jogo", "initial"),
      entry("jogar", "initial"),
      entry("jantar", "initial"),
      entry("jardim", "initial"),
      entry("jaqueta", "initial"),
      entry("joelho", "initial"),
      entry("jovem", "initial"),
      entry("junto", "initial"),
      entry("junho", "initial"),
      entry("feijão", "inside"),
      entry("beijo", "inside"),
      entry("loja", "inside"),
      entry("sujo", "inside"),
      entry("laranja", "inside"),
      entry("viajar", "inside"),
    ],
  },
  x: {
    risk: "sensitive",
    notes: "Use only common x words with a stable sh-like sound for now.",
    words: [
      entry("xícara", "initial"),
      entry("xarope", "initial"),
      entry("xadrez", "initial"),
      entry("xampu", "initial"),
      entry("xale", "initial"),
      entry("peixe", "inside"),
      entry("caixa", "inside"),
      entry("baixo", "inside"),
      entry("deixar", "inside"),
      entry("lixo", "inside"),
      entry("mexer", "inside"),
    ],
  },
  n: {
    risk: "sensitive",
    notes: "Keep plain n separate from nh practice.",
    words: [
      entry("neto", "initial"),
      entry("nada", "initial"),
      entry("nove", "initial"),
      entry("novo", "initial"),
      entry("nome", "initial"),
      entry("noite", "initial"),
      entry("nariz", "initial"),
      entry("nuvem", "initial"),
      entry("nadar", "initial"),
      entry("Nina", "initial"),
      entry("nossa", "initial"),
      entry("nunca", "initial"),
      entry("nota", "initial"),
      entry("norte", "initial"),
      entry("menino", "inside"),
      entry("menina", "inside"),
      entry("banana", "inside"),
      entry("janela", "inside"),
      entry("caneta", "inside"),
      entry("panela", "inside"),
      entry("boneca", "inside"),
      entry("telefone", "inside"),
      entry("pequeno", "inside"),
      entry("bonito", "inside"),
      entry("cantar", "inside"),
      entry("dançar", "inside"),
      entry("ensinar", "inside"),
      entry("brincar", "inside"),
    ],
  },
  nh: {
    risk: "sensitive",
    notes: "The Brazilian Portuguese nh sound is usually written nh and rarely starts a word.",
    words: [
      entry("ninho", "initial"),
      entry("minha", "initial"),
      entry("manhã", "initial"),
      entry("banho", "initial"),
      entry("sonho", "initial"),
      entry("tenho", "initial"),
      entry("venha", "initial"),
      entry("unha", "initial"),
      entry("cozinha", "inside"),
      entry("galinha", "inside"),
      entry("caminho", "inside"),
      entry("sozinho", "inside"),
      entry("desenho", "inside"),
      entry("carinho", "inside"),
      entry("dinheiro", "inside"),
      entry("vizinho", "inside"),
      entry("sobrinha", "inside"),
      entry("sobrinho", "inside"),
      entry("companhia", "inside", "extra"),
      entry("linha", "inside", "extra"),
    ],
  },
  lh: {
    risk: "sensitive",
    notes: "The Brazilian Portuguese lh sound is written lh and rarely starts a word.",
    words: [
      entry("olho", "initial"),
      entry("filho", "initial"),
      entry("filha", "initial"),
      entry("milho", "initial"),
      entry("folha", "initial"),
      entry("molho", "initial"),
      entry("velho", "initial"),
      entry("toalha", "initial"),
      entry("abelha", "inside"),
      entry("ilha", "inside"),
      entry("trabalho", "inside"),
      entry("barulho", "inside"),
      entry("agulha", "inside"),
      entry("colher", "inside"),
      entry("melhor", "inside"),
      entry("molhado", "inside"),
      entry("vermelho", "inside"),
      entry("espelho", "inside"),
      entry("bilhete", "inside", "extra"),
      entry("alho", "inside", "extra"),
    ],
  },
  ch: {
    risk: "sensitive",
    notes: "For Brazilian Portuguese ch, use words written with ch and avoid mixing with x words for now.",
    words: [
      entry("chá", "initial"),
      entry("chave", "initial"),
      entry("chuva", "initial"),
      entry("chão", "initial"),
      entry("chapéu", "initial"),
      entry("chefe", "initial"),
      entry("cheio", "initial"),
      entry("chegar", "initial"),
      entry("chamar", "initial"),
      entry("fechar", "initial"),
      entry("chorar", "initial"),
      entry("chutar", "initial"),
      entry("chocolate", "initial"),
      entry("mochila", "inside"),
      entry("lanche", "inside"),
      entry("cachorro", "inside"),
      entry("bolacha", "inside"),
      entry("fechado", "inside"),
      entry("machucado", "inside"),
      entry("fichário", "inside", "extra"),
      entry("bicho", "inside", "extra"),
    ],
  },
  "ão": {
    risk: "sensitive",
    notes: "Use common Brazilian Portuguese words with the nasal ão ending.",
    words: [
      entry("pão", "initial"),
      entry("mão", "initial"),
      entry("chão", "initial"),
      entry("cão", "initial"),
      entry("irmão", "initial"),
      entry("mamão", "initial"),
      entry("limão", "initial"),
      entry("fogão", "initial"),
      entry("balão", "inside"),
      entry("coração", "inside"),
      entry("avião", "inside"),
      entry("lição", "inside"),
      entry("canção", "inside"),
      entry("atenção", "inside"),
      entry("refeição", "inside"),
      entry("estação", "inside"),
      entry("televisão", "inside"),
      entry("informação", "inside"),
      entry("brincalhão", "inside", "extra"),
      entry("caminhão", "inside", "extra"),
    ],
  },
};

function normalizeSound(value: string): string {
  return value.trim().toLocaleLowerCase();
}

function normalizeWord(value: string): string {
  return value.trim().toLocaleLowerCase();
}

export function getNorwegianSoundWordEntries(sound: string): SoundWordEntry[] {
  return NORWEGIAN_SOUND_WORD_BANKS[normalizeSound(sound)]?.words ?? [];
}

export function getNorwegianSoundWords(sound: string, count: number): string[] {
  if (count <= 0) return [];
  const entries = getNorwegianSoundWordEntries(sound);
  return entries.slice(0, count).map((item) => item.word);
}

export function getNorwegianInsideSoundWords(sound: string): string[] {
  return getNorwegianSoundWordEntries(sound)
    .filter((item) => item.position === "inside")
    .map((item) => item.word);
}

export function isApprovedNorwegianSoundWord(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  return getNorwegianSoundWordEntries(sound).some((item) => normalizeWord(item.word) === normalizedWord);
}

export function norwegianSoundWordStartsWithSound(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  const normalizedSound = normalizeSound(sound);
  const entry = getNorwegianSoundWordEntries(sound).find((item) => normalizeWord(item.word) === normalizedWord);
  if (entry) return entry.position === "initial";
  return normalizedWord.startsWith(normalizedSound);
}

export function norwegianSoundWordContainsSound(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  const normalizedSound = normalizeSound(sound);
  return isApprovedNorwegianSoundWord(sound, word) || normalizedWord.includes(normalizedSound);
}

export function getNorwegianSoundBank(sound: string): SoundWordBank | null {
  return NORWEGIAN_SOUND_WORD_BANKS[normalizeSound(sound)] ?? null;
}

export function getPortugueseSoundWordEntries(sound: string): SoundWordEntry[] {
  return PORTUGUESE_SOUND_WORD_BANKS[normalizeSound(sound)]?.words ?? [];
}

export function getPortugueseSoundWords(sound: string, count: number): string[] {
  if (count <= 0) return [];
  const entries = getPortugueseSoundWordEntries(sound);
  return entries.slice(0, count).map((item) => item.word);
}

export function getPortugueseInsideSoundWords(sound: string): string[] {
  return getPortugueseSoundWordEntries(sound)
    .filter((item) => item.position === "inside")
    .map((item) => item.word);
}

export function isApprovedPortugueseSoundWord(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  return getPortugueseSoundWordEntries(sound).some((item) => normalizeWord(item.word) === normalizedWord);
}

export function portugueseSoundWordStartsWithSound(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  const normalizedSound = normalizeSound(sound);
  const entry = getPortugueseSoundWordEntries(sound).find((item) => normalizeWord(item.word) === normalizedWord);
  if (entry) return entry.position === "initial";
  return normalizedWord.startsWith(normalizedSound);
}

export function portugueseSoundWordContainsSound(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  const normalizedSound = normalizeSound(sound);
  return isApprovedPortugueseSoundWord(sound, word) || normalizedWord.includes(normalizedSound);
}

export function getPortugueseSoundBank(sound: string): SoundWordBank | null {
  return PORTUGUESE_SOUND_WORD_BANKS[normalizeSound(sound)] ?? null;
}
