export type SoundWordPosition = "initial" | "inside";
export type SoundWordLevel = "core" | "extra";
export type SoundRisk = "safe" | "sensitive";

export type SoundWordEntry = {
  word: string;
  position: SoundWordPosition;
  level: SoundWordLevel;
};

export type SoundWordBank = {
  risk: SoundRisk;
  notes?: string;
  words: SoundWordEntry[];
};

function entry(word: string, position: SoundWordPosition, level: SoundWordLevel = "core"): SoundWordEntry {
  return { word, position, level };
}

export const NORWEGIAN_SOUND_WORD_BANKS: Record<string, SoundWordBank> = {
  s: {
    risk: "safe",
    words: [
      entry("sol", "initial"),
      entry("saft", "initial"),
      entry("seng", "initial"),
      entry("sekk", "initial"),
      entry("sko", "initial"),
      entry("suppe", "initial"),
      entry("sitte", "initial"),
      entry("se", "initial"),
      entry("si", "initial"),
      entry("sang", "initial"),
      entry("sommer", "initial"),
      entry("skole", "initial"),
      entry("stol", "initial"),
      entry("sulten", "initial"),
      entry("søt", "initial"),
      entry("buss", "inside"),
      entry("hus", "inside"),
      entry("lese", "inside"),
      entry("pose", "inside"),
      entry("danse", "inside"),
      entry("fisk", "inside"),
      entry("ost", "inside"),
      entry("klasse", "inside"),
      entry("bestemor", "inside"),
      entry("hest", "inside"),
      entry("is", "inside"),
    ],
  },
  m: {
    risk: "safe",
    words: [
      entry("mat", "initial"),
      entry("mor", "initial"),
      entry("mus", "initial"),
      entry("melk", "initial"),
      entry("mål", "initial"),
      entry("mye", "initial"),
      entry("min", "initial"),
      entry("mitt", "initial"),
      entry("måne", "initial"),
      entry("mann", "initial"),
      entry("mamma", "initial"),
      entry("morgen", "initial"),
      entry("munn", "initial"),
      entry("med", "initial"),
      entry("møter", "initial"),
      entry("rom", "inside"),
      entry("hjem", "inside"),
      entry("sommer", "inside"),
      entry("familie", "inside"),
      entry("komme", "inside"),
      entry("lampe", "inside"),
      entry("nummer", "inside"),
      entry("gammel", "inside"),
      entry("klemme", "inside"),
      entry("lomme", "inside"),
      entry("tomat", "inside"),
    ],
  },
  a: {
    risk: "safe",
    words: [
      entry("and", "initial"),
      entry("ape", "initial"),
      entry("arm", "initial"),
      entry("ark", "initial"),
      entry("alle", "initial"),
      entry("Anna", "initial"),
      entry("Ali", "initial"),
      entry("av", "initial"),
      entry("at", "initial"),
      entry("appelsin", "initial"),
      entry("arbeid", "initial"),
      entry("ansikt", "initial"),
      entry("aldri", "initial"),
      entry("alltid", "initial"),
      entry("mat", "inside"),
      entry("Sara", "inside"),
      entry("banan", "inside"),
      entry("kake", "inside"),
      entry("glad", "inside"),
      entry("dag", "inside"),
      entry("pappa", "inside"),
      entry("mamma", "inside"),
      entry("familie", "inside"),
      entry("salat", "inside"),
      entry("hatt", "inside"),
      entry("jakke", "inside"),
    ],
  },
  b: {
    risk: "safe",
    words: [
      entry("bil", "initial"),
      entry("bok", "initial"),
      entry("ball", "initial"),
      entry("bord", "initial"),
      entry("buss", "initial"),
      entry("barn", "initial"),
      entry("brød", "initial"),
      entry("båt", "initial"),
      entry("ben", "initial"),
      entry("blå", "initial"),
      entry("butikk", "initial"),
      entry("bamse", "initial"),
      entry("bade", "initial"),
      entry("bilde", "initial"),
      entry("bak", "initial"),
      entry("jobb", "inside"),
      entry("kube", "inside"),
      entry("robot", "inside"),
      entry("tabell", "inside"),
      entry("nabo", "inside"),
      entry("skrubbe", "inside", "extra"),
      entry("krabbe", "inside"),
      entry("lommebok", "inside"),
    ],
  },
  d: {
    risk: "safe",
    words: [
      entry("dag", "initial"),
      entry("du", "initial"),
      entry("din", "initial"),
      entry("dyr", "initial"),
      entry("dør", "initial"),
      entry("dans", "initial"),
      entry("dukke", "initial"),
      entry("drue", "initial"),
      entry("drikke", "initial"),
      entry("dele", "initial"),
      entry("der", "initial"),
      entry("dame", "initial"),
      entry("datter", "initial"),
      entry("data", "initial"),
      entry("dusj", "initial"),
      entry("skade", "inside"),
      entry("bilde", "inside"),
      entry("side", "inside"),
      entry("hode", "inside"),
      entry("middag", "inside"),
      entry("bade", "inside"),
      entry("nede", "inside"),
      entry("redde", "inside"),
      entry("rydde", "inside"),
      entry("lyd", "inside"),
    ],
  },
  f: {
    risk: "safe",
    words: [
      entry("far", "initial"),
      entry("fisk", "initial"),
      entry("fot", "initial"),
      entry("fin", "initial"),
      entry("fugl", "initial"),
      entry("fem", "initial"),
      entry("frokost", "initial"),
      entry("frukt", "initial"),
      entry("farge", "initial"),
      entry("får", "initial"),
      entry("familie", "initial"),
      entry("finner", "initial"),
      entry("fart", "initial"),
      entry("fryser", "initial"),
      entry("følge", "initial"),
      entry("kaffe", "inside"),
      entry("sofa", "inside"),
      entry("telefon", "inside"),
      entry("vaffel", "inside"),
      entry("skuff", "inside"),
      entry("tøff", "inside"),
      entry("loft", "inside"),
      entry("saft", "inside"),
      entry("ofte", "inside"),
      entry("lufte", "inside"),
    ],
  },
  g: {
    risk: "safe",
    words: [
      entry("gå", "initial"),
      entry("god", "initial"),
      entry("gul", "initial"),
      entry("gris", "initial"),
      entry("gutt", "initial"),
      entry("gate", "initial"),
      entry("gave", "initial"),
      entry("genser", "initial"),
      entry("glass", "initial"),
      entry("glede", "initial"),
      entry("grøt", "initial"),
      entry("grønn", "initial"),
      entry("gammel", "initial"),
      entry("gitar", "initial"),
      entry("gulrot", "initial"),
      entry("dag", "inside"),
      entry("tog", "inside"),
      entry("hage", "inside"),
      entry("mage", "inside"),
      entry("farge", "inside"),
      entry("morgen", "inside"),
      entry("legge", "inside"),
      entry("ligge", "inside"),
      entry("fugl", "inside"),
      entry("rolig", "inside"),
      entry("sag", "inside"),
    ],
  },
  k: {
    risk: "sensitive",
    notes: "Plain k should not mix with kj/skj words.",
    words: [
      entry("katt", "initial"),
      entry("kake", "initial"),
      entry("kopp", "initial"),
      entry("kul", "initial"),
      entry("kan", "initial"),
      entry("kommer", "initial"),
      entry("kald", "initial"),
      entry("kort", "initial"),
      entry("klasse", "initial"),
      entry("klokke", "initial"),
      entry("kropp", "initial"),
      entry("klem", "initial"),
      entry("kveld", "initial"),
      entry("ku", "initial"),
      entry("bok", "inside"),
      entry("tak", "inside"),
      entry("pakke", "inside"),
      entry("sokker", "inside"),
      entry("drikke", "inside"),
      entry("skole", "inside"),
      entry("voksen", "inside"),
      entry("lek", "inside"),
      entry("frokost", "inside"),
      entry("matpakke", "inside"),
      entry("jakke", "inside"),
    ],
  },
  n: {
    risk: "safe",
    words: [
      entry("natt", "initial"),
      entry("nese", "initial"),
      entry("navn", "initial"),
      entry("ni", "initial"),
      entry("ny", "initial"),
      entry("norsk", "initial"),
      entry("nøkkel", "initial"),
      entry("nabo", "initial"),
      entry("natur", "initial"),
      entry("nå", "initial"),
      entry("nær", "initial"),
      entry("ned", "initial"),
      entry("noen", "initial"),
      entry("Nina", "initial"),
      entry("notat", "initial"),
      entry("banan", "inside"),
      entry("vann", "inside"),
      entry("venn", "inside"),
      entry("mann", "inside"),
      entry("hund", "inside"),
      entry("kanin", "inside"),
      entry("måne", "inside"),
      entry("panne", "inside"),
      entry("fin", "inside"),
      entry("grønn", "inside"),
      entry("barn", "inside"),
    ],
  },
  e: {
    risk: "safe",
    words: [
      entry("egg", "initial"),
      entry("en", "initial"),
      entry("et", "initial"),
      entry("eple", "initial"),
      entry("elefant", "initial"),
      entry("elleve", "initial"),
      entry("etter", "initial"),
      entry("elev", "initial"),
      entry("egen", "initial"),
      entry("enkel", "initial"),
      entry("elsker", "initial"),
      entry("eske", "initial"),
      entry("elv", "initial"),
      entry("ende", "initial"),
      entry("er", "initial"),
      entry("se", "inside"),
      entry("leke", "inside"),
      entry("lese", "inside"),
      entry("seng", "inside"),
      entry("bestemor", "inside"),
      entry("venn", "inside"),
      entry("melk", "inside"),
      entry("hest", "inside"),
      entry("lek", "inside"),
      entry("pen", "inside"),
      entry("del", "inside"),
    ],
  },
  o: {
    risk: "safe",
    words: [
      entry("ost", "initial"),
      entry("ord", "initial"),
      entry("Ole", "initial"),
      entry("Oda", "initial"),
      entry("opp", "initial"),
      entry("onkel", "initial"),
      entry("onsdag", "initial"),
      entry("område", "initial"),
      entry("okse", "initial"),
      entry("om", "initial"),
      entry("sol", "inside"),
      entry("sko", "inside"),
      entry("bok", "inside"),
      entry("bord", "inside"),
      entry("mor", "inside"),
      entry("bror", "inside"),
      entry("pose", "inside"),
      entry("jobb", "inside"),
      entry("robot", "inside"),
      entry("foto", "inside"),
      entry("to", "inside"),
      entry("ro", "inside"),
      entry("bo", "inside"),
      entry("bor", "inside"),
      entry("stor", "inside"),
      entry("god", "inside"),
    ],
  },
  u: {
    risk: "safe",
    words: [
      entry("ut", "initial"),
      entry("ull", "initial"),
      entry("uke", "initial"),
      entry("under", "initial"),
      entry("ute", "initial"),
      entry("uten", "initial"),
      entry("ulv", "initial"),
      entry("Ulla", "initial"),
      entry("ugle", "initial"),
      entry("usikker", "initial"),
      entry("univers", "initial", "extra"),
      entry("unik", "initial", "extra"),
      entry("utstyr", "initial"),
      entry("hus", "inside"),
      entry("buss", "inside"),
      entry("suppe", "inside"),
      entry("gul", "inside"),
      entry("tur", "inside"),
      entry("hund", "inside"),
      entry("lunsj", "inside"),
      entry("frukt", "inside"),
      entry("brun", "inside"),
      entry("mus", "inside"),
      entry("du", "inside"),
    ],
  },
  æ: {
    risk: "safe",
    words: [
      entry("ærlig", "initial"),
      entry("ærend", "initial"),
      entry("her", "initial"),
      entry("der", "initial"),
      entry("er", "initial"),
      entry("bær", "inside"),
      entry("vær", "inside"),
      entry("nær", "inside"),
      entry("lærer", "inside"),
      entry("klær", "inside"),
      entry("tær", "inside"),
      entry("kjær", "inside"),
      entry("været", "inside"),
      entry("stjerne", "inside"),
      entry("sær", "inside", "extra"),
      entry("ære", "inside", "extra"),
    ],
  },
  ø: {
    risk: "safe",
    words: [
      entry("øye", "initial"),
      entry("øre", "initial"),
      entry("øy", "initial"),
      entry("øve", "initial"),
      entry("ønske", "initial"),
      entry("øse", "initial"),
      entry("søt", "inside"),
      entry("brød", "inside"),
      entry("grøt", "inside"),
      entry("følge", "inside"),
      entry("møte", "inside"),
      entry("rød", "inside"),
      entry("grønn", "inside"),
      entry("løpe", "inside"),
      entry("høre", "inside"),
      entry("bøker", "inside"),
      entry("dør", "inside"),
      entry("søster", "inside"),
      entry("høne", "inside"),
      entry("skjørt", "inside"),
      entry("kjøkken", "inside"),
      entry("kjøpe", "inside"),
    ],
  },
  å: {
    risk: "safe",
    words: [
      entry("å", "initial"),
      entry("år", "initial"),
      entry("åtte", "initial"),
      entry("ål", "initial", "extra"),
      entry("båt", "inside"),
      entry("blå", "inside"),
      entry("får", "inside"),
      entry("går", "inside"),
      entry("står", "inside"),
      entry("må", "inside"),
      entry("nå", "inside"),
      entry("så", "inside"),
      entry("på", "inside"),
      entry("låne", "inside"),
      entry("måne", "inside"),
      entry("hår", "inside"),
      entry("tå", "inside"),
      entry("våt", "inside"),
      entry("grå", "inside"),
      entry("små", "inside"),
    ],
  },
  sj: {
    risk: "sensitive",
    notes: "The Norwegian sj sound can be written sj, skj and some sk before front vowels.",
    words: [
      entry("sjakk", "initial"),
      entry("sjal", "initial"),
      entry("sjef", "initial"),
      entry("sjekk", "initial"),
      entry("sjekke", "initial"),
      entry("sjekkliste", "initial", "extra"),
      entry("sjokolade", "initial"),
      entry("sjokoladepudding", "initial", "extra"),
      entry("sjø", "initial"),
      entry("sjømann", "initial", "extra"),
      entry("sjåfør", "initial"),
      entry("sjampo", "initial"),
      entry("sjarm", "initial", "extra"),
      entry("skjegg", "initial"),
      entry("skje", "initial"),
      entry("skjell", "initial"),
      entry("skjerm", "initial"),
      entry("skjorte", "initial"),
      entry("skjørt", "initial"),
      entry("skjære", "initial"),
      entry("ski", "initial"),
      entry("skilt", "initial"),
      entry("skinke", "initial"),
      entry("skinn", "initial", "extra"),
      entry("sky", "initial"),
      entry("skygge", "initial"),
      entry("kanskje", "inside"),
      entry("maskin", "inside"),
      entry("dusje", "inside"),
      entry("garasje", "inside"),
      entry("brosjyre", "inside", "extra"),
    ],
  },
  kj: {
    risk: "sensitive",
    notes: "Keep kj separate from k and sj/skj words.",
    words: [
      entry("kjole", "initial"),
      entry("kjøkken", "initial"),
      entry("kjøtt", "initial"),
      entry("kjeks", "initial"),
      entry("kjekk", "initial"),
      entry("kjenne", "initial"),
      entry("kjøpe", "initial"),
      entry("kjøre", "initial"),
      entry("kjede", "initial"),
      entry("kjeller", "initial"),
      entry("kjølig", "initial", "extra"),
      entry("kjapp", "initial"),
      entry("Kjell", "initial"),
      entry("kjele", "initial"),
      entry("kjæledyr", "initial"),
      entry("kjøleskap", "initial"),
      entry("kjempe", "initial"),
      entry("kjempefin", "initial"),
      entry("kjent", "initial"),
      entry("kjenner", "initial"),
      entry("kjempestor", "initial", "extra"),
      entry("bikkje", "inside"),
    ],
  },
};

function normalizeSound(value: string): string {
  return value.trim().toLocaleLowerCase();
}

function normalizeWord(value: string): string {
  return value.trim().toLocaleLowerCase();
}

export function getNorwegianSoundWordEntries(sound: string): SoundWordEntry[] {
  return NORWEGIAN_SOUND_WORD_BANKS[normalizeSound(sound)]?.words ?? [];
}

export function getNorwegianSoundWords(sound: string, count: number): string[] {
  if (count <= 0) return [];
  const entries = getNorwegianSoundWordEntries(sound);
  return entries.slice(0, count).map((item) => item.word);
}

export function getNorwegianInsideSoundWords(sound: string): string[] {
  return getNorwegianSoundWordEntries(sound)
    .filter((item) => item.position === "inside")
    .map((item) => item.word);
}

export function isApprovedNorwegianSoundWord(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  return getNorwegianSoundWordEntries(sound).some((item) => normalizeWord(item.word) === normalizedWord);
}

export function norwegianSoundWordStartsWithSound(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  const normalizedSound = normalizeSound(sound);
  const entry = getNorwegianSoundWordEntries(sound).find((item) => normalizeWord(item.word) === normalizedWord);
  if (entry) return entry.position === "initial";
  return normalizedWord.startsWith(normalizedSound);
}

export function norwegianSoundWordContainsSound(sound: string, word: string): boolean {
  const normalizedWord = normalizeWord(word);
  const normalizedSound = normalizeSound(sound);
  return isApprovedNorwegianSoundWord(sound, word) || normalizedWord.includes(normalizedSound);
}

export function getNorwegianSoundBank(sound: string): SoundWordBank | null {
  return NORWEGIAN_SOUND_WORD_BANKS[normalizeSound(sound)] ?? null;
}
